/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget *
create_MainFrame (void)
{
  GtkWidget *MainFrame;
  GdkPixbuf *MainFrame_icon_pixbuf;
  GtkWidget *MainTable;
  GtkWidget *alignment1;
  GtkWidget *MainMenu;
  GtkWidget *menuitem1;
  GtkWidget *image454;
  GtkWidget *menuitem1_menu;
  GtkWidget *new_project;
  GtkWidget *image455;
  GtkWidget *open_project;
  GtkWidget *image456;
  GtkWidget *Save;
  GtkWidget *image457;
  GtkWidget *Save_As;
  GtkWidget *image458;
  GtkWidget *separatormenuitem1;
  GtkWidget *Quitt;
  GtkWidget *image459;
  GtkWidget *DeviceData;
  GtkWidget *image460;
  GtkWidget *DeviceData_menu;
  GtkWidget *ShowDeviceData;
  GtkWidget *image461;
  GtkWidget *editDeviceData;
  GtkWidget *image462;
  GtkWidget *ConvertDeviceData;
  GtkWidget *image463;
  GtkWidget *ImportXMLDeviceData;
  GtkWidget *image464;
  GtkWidget *ExportXMLDeviceData;
  GtkWidget *image465;
  GtkWidget *About;
  GtkWidget *image466;
  GtkWidget *PanelLeft;
  GtkWidget *PanelRight;
  GtkWidget *ScrolledWindowLeft;
  GtkWidget *ProjectTree;
  GtkWidget *vbox1;
  GtkWidget *handlebox_toolbar;
  GtkWidget *eventbox_Toolbar;
  GtkWidget *hbuttonbox1;
  GtkWidget *button_building;
  GtkWidget *alignment6;
  GtkWidget *hbox5;
  GtkWidget *image154;
  GtkWidget *label10;
  GtkWidget *button_floor;
  GtkWidget *alignment7;
  GtkWidget *hbox6;
  GtkWidget *image155;
  GtkWidget *label11;
  GtkWidget *button_room;
  GtkWidget *alignment8;
  GtkWidget *hbox7;
  GtkWidget *image156;
  GtkWidget *label12;
  GtkWidget *button_junction;
  GtkWidget *alignment9;
  GtkWidget *hbox8;
  GtkWidget *image157;
  GtkWidget *label13;
  GtkWidget *scrolledwindow4;
  GtkWidget *viewport1;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  MainFrame = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MainFrame), _("Freebus-ETS"));
  gtk_window_set_position (GTK_WINDOW (MainFrame), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (MainFrame), 1280, 980);
  MainFrame_icon_pixbuf = create_pixbuf ("freebuslq5.png");
  if (MainFrame_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (MainFrame), MainFrame_icon_pixbuf);
      gdk_pixbuf_unref (MainFrame_icon_pixbuf);
    }

  MainTable = gtk_table_new (4, 1, FALSE);
  gtk_widget_show (MainTable);
  gtk_container_add (GTK_CONTAINER (MainFrame), MainTable);

  alignment1 = gtk_alignment_new (0, 0, 1, 0);
  gtk_widget_show (alignment1);
  gtk_table_attach (GTK_TABLE (MainTable), alignment1, 0, 1, 0, 1,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (GTK_FILL), 0, 0);

  MainMenu = gtk_menu_bar_new ();
  gtk_widget_show (MainMenu);
  gtk_container_add (GTK_CONTAINER (alignment1), MainMenu);

  menuitem1 = gtk_image_menu_item_new_with_mnemonic (_("_Datei"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (MainMenu), menuitem1);

  image454 = create_pixmap (MainFrame, "file-manager.png");
  gtk_widget_show (image454);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuitem1), image454);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  new_project = gtk_image_menu_item_new_with_mnemonic (_("_Neues Projekt"));
  gtk_widget_show (new_project);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), new_project);
  gtk_tooltips_set_tip (tooltips, new_project, _("erzeugt ein neues Projekt"),
			NULL);
  gtk_widget_add_accelerator (new_project, "activate", accel_group, GDK_N,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image455 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image455);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (new_project), image455);

  open_project =
    gtk_image_menu_item_new_with_mnemonic (_("Ã\226ffne Pr_ojekt"));
  gtk_widget_show (open_project);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), open_project);
  gtk_tooltips_set_tip (tooltips, open_project,
			_("Ã\266ffnet ein vorhandenes Projekt"), NULL);
  gtk_widget_add_accelerator (open_project, "activate", accel_group, GDK_O,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image456 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image456);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (open_project),
				 image456);

  Save = gtk_image_menu_item_new_with_mnemonic (_("_Speichern"));
  gtk_widget_show (Save);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), Save);
  gtk_tooltips_set_tip (tooltips, Save,
			_("speichert Projekt unter aktuellen Namen"), NULL);
  gtk_widget_add_accelerator (Save, "activate", accel_group, GDK_S,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image457 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image457);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (Save), image457);

  Save_As = gtk_image_menu_item_new_with_mnemonic (_("S_peichern unter"));
  gtk_widget_show (Save_As);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), Save_As);
  gtk_tooltips_set_tip (tooltips, Save_As,
			_("speichert das Projekt unter einem neuen Namen"),
			NULL);
  gtk_widget_add_accelerator (Save_As, "activate", accel_group, GDK_S,
			      GDK_CONTROL_MASK | GDK_SHIFT_MASK,
			      GTK_ACCEL_VISIBLE);

  image458 = gtk_image_new_from_stock ("gtk-save-as", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image458);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (Save_As), image458);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  Quitt = gtk_image_menu_item_new_with_mnemonic (_("_Beenden"));
  gtk_widget_show (Quitt);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), Quitt);
  gtk_tooltips_set_tip (tooltips, Quitt, _("beendet das schÃ\266ne Programm"),
			NULL);
  gtk_widget_add_accelerator (Quitt, "activate", accel_group, GDK_Q,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image459 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image459);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (Quitt), image459);

  DeviceData = gtk_image_menu_item_new_with_mnemonic (_("_GerÃ¤tedaten"));
  gtk_widget_show (DeviceData);
  gtk_container_add (GTK_CONTAINER (MainMenu), DeviceData);

  image460 = create_pixmap (MainFrame, "package-x-generic.png");
  gtk_widget_show (image460);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (DeviceData), image460);

  DeviceData_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (DeviceData), DeviceData_menu);

  ShowDeviceData = gtk_image_menu_item_new_with_mnemonic (_("_Anzeigen"));
  gtk_widget_show (ShowDeviceData);
  gtk_container_add (GTK_CONTAINER (DeviceData_menu), ShowDeviceData);
  gtk_tooltips_set_tip (tooltips, ShowDeviceData,
			_
			("zeigt die im Projekt verfÃ¼gbaren GerÃ¤testammdaten an"),
			NULL);
  gtk_widget_add_accelerator (ShowDeviceData, "activate", accel_group, GDK_A,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image461 = create_pixmap (MainFrame, "show_DeviceData.png");
  gtk_widget_show (image461);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (ShowDeviceData),
				 image461);

  editDeviceData = gtk_image_menu_item_new_with_mnemonic (_("_Bearbeiten"));
  gtk_widget_show (editDeviceData);
  gtk_container_add (GTK_CONTAINER (DeviceData_menu), editDeviceData);
  gtk_tooltips_set_tip (tooltips, editDeviceData,
			_("erstellen und bearbeiten von GerÃ¤testammdaten"),
			NULL);
  gtk_widget_add_accelerator (editDeviceData, "activate", accel_group, GDK_B,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image462 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image462);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (editDeviceData),
				 image462);

  ConvertDeviceData =
    gtk_image_menu_item_new_with_mnemonic (_("_Konvertieren"));
  gtk_widget_show (ConvertDeviceData);
  gtk_container_add (GTK_CONTAINER (DeviceData_menu), ConvertDeviceData);
  gtk_tooltips_set_tip (tooltips, ConvertDeviceData,
			_
			("Konvertiert vorhandene *.vd_ Dateien in ein XML Format"),
			NULL);
  gtk_widget_add_accelerator (ConvertDeviceData, "activate", accel_group,
			      GDK_K, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image463 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image463);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (ConvertDeviceData),
				 image463);

  ImportXMLDeviceData =
    gtk_image_menu_item_new_with_mnemonic (_("_Import von XML"));
  gtk_widget_show (ImportXMLDeviceData);
  gtk_container_add (GTK_CONTAINER (DeviceData_menu), ImportXMLDeviceData);
  gtk_tooltips_set_tip (tooltips, ImportXMLDeviceData,
			_
			("importiert GerÃ¤tedaten aus einer XML-Datei in die Datenbank"),
			NULL);
  gtk_widget_add_accelerator (ImportXMLDeviceData, "activate", accel_group,
			      GDK_I, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image464 =
    gtk_image_new_from_stock ("gtk-media-rewind", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image464);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (ImportXMLDeviceData),
				 image464);

  ExportXMLDeviceData =
    gtk_image_menu_item_new_with_mnemonic (_("_Export nach XML"));
  gtk_widget_show (ExportXMLDeviceData);
  gtk_container_add (GTK_CONTAINER (DeviceData_menu), ExportXMLDeviceData);
  gtk_tooltips_set_tip (tooltips, ExportXMLDeviceData,
			_("exportiert GerÃ¤testammdaten in eine XML-Datei"),
			NULL);
  gtk_widget_add_accelerator (ExportXMLDeviceData, "activate", accel_group,
			      GDK_E, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image465 =
    gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image465);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (ExportXMLDeviceData),
				 image465);

  About = gtk_image_menu_item_new_with_mnemonic (_("Ã\234_ber..."));
  gtk_widget_show (About);
  gtk_container_add (GTK_CONTAINER (MainMenu), About);

  image466 = create_pixmap (MainFrame, "dialog-information.png");
  gtk_widget_show (image466);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (About), image466);

  PanelLeft = gtk_hpaned_new ();
  gtk_widget_show (PanelLeft);
  gtk_table_attach (GTK_TABLE (MainTable), PanelLeft, 0, 1, 1, 3,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_paned_set_position (GTK_PANED (PanelLeft), 0);

  PanelRight = gtk_hpaned_new ();
  gtk_widget_show (PanelRight);
  gtk_paned_pack2 (GTK_PANED (PanelLeft), PanelRight, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (PanelRight), 260);

  ScrolledWindowLeft = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (ScrolledWindowLeft);
  gtk_paned_pack1 (GTK_PANED (PanelRight), ScrolledWindowLeft, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (ScrolledWindowLeft),
				  GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW
				       (ScrolledWindowLeft), GTK_SHADOW_IN);

  ProjectTree = gtk_tree_view_new ();
  gtk_widget_show (ProjectTree);
  gtk_container_add (GTK_CONTAINER (ScrolledWindowLeft), ProjectTree);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_paned_pack2 (GTK_PANED (PanelRight), vbox1, TRUE, TRUE);

  handlebox_toolbar = gtk_handle_box_new ();
  gtk_widget_show (handlebox_toolbar);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox_toolbar, FALSE, FALSE, 3);
  gtk_handle_box_set_shadow_type (GTK_HANDLE_BOX (handlebox_toolbar),
				  GTK_SHADOW_NONE);

  eventbox_Toolbar = gtk_event_box_new ();
  gtk_widget_show (eventbox_Toolbar);
  gtk_container_add (GTK_CONTAINER (handlebox_toolbar), eventbox_Toolbar);
  gtk_widget_set_events (eventbox_Toolbar, GDK_BUTTON_PRESS_MASK);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_container_add (GTK_CONTAINER (eventbox_Toolbar), hbuttonbox1);
  gtk_widget_set_size_request (hbuttonbox1, -1, 45);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1),
			     GTK_BUTTONBOX_START);

  button_building = gtk_button_new ();
  gtk_widget_show (button_building);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_building);
  gtk_widget_set_size_request (button_building, -1, 40);
  GTK_WIDGET_SET_FLAGS (button_building, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_building,
			_("FÃ¼ge ein GebÃ¤ude hinzu"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button_building), GTK_RELIEF_NONE);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_building), alignment6);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox5);

  image154 = create_pixmap (MainFrame, "building.png");
  gtk_widget_show (image154);
  gtk_box_pack_start (GTK_BOX (hbox5), image154, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_(" GebÃ¤ude"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  button_floor = gtk_button_new ();
  gtk_widget_show (button_floor);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_floor);
  gtk_widget_set_size_request (button_floor, -1, 40);
  GTK_WIDGET_SET_FLAGS (button_floor, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_floor, _("FÃ¼ge eine Etage hinzu"),
			NULL);
  gtk_button_set_relief (GTK_BUTTON (button_floor), GTK_RELIEF_NONE);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_floor), alignment7);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox6);

  image155 = create_pixmap (MainFrame, "floor.png");
  gtk_widget_show (image155);
  gtk_box_pack_start (GTK_BOX (hbox6), image155, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_(" Etage"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox6), label11, FALSE, FALSE, 0);

  button_room = gtk_button_new ();
  gtk_widget_show (button_room);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_room);
  gtk_widget_set_size_request (button_room, -1, 40);
  GTK_WIDGET_SET_FLAGS (button_room, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_room, _("fÃ¼ge einen Raum hinzu"),
			NULL);
  gtk_button_set_relief (GTK_BUTTON (button_room), GTK_RELIEF_NONE);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_room), alignment8);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox7);

  image156 = create_pixmap (MainFrame, "room.png");
  gtk_widget_show (image156);
  gtk_box_pack_start (GTK_BOX (hbox7), image156, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_(" Raum"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox7), label12, FALSE, FALSE, 0);

  button_junction = gtk_button_new ();
  gtk_widget_show (button_junction);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_junction);
  gtk_widget_set_size_request (button_junction, -1, 40);
  GTK_WIDGET_SET_FLAGS (button_junction, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_junction,
			_("fÃ¼ge eine Verteiler hnizu"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button_junction), GTK_RELIEF_NONE);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_junction), alignment9);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox8);

  image157 = create_pixmap (MainFrame, "junctionbox.png");
  gtk_widget_show (image157);
  gtk_box_pack_start (GTK_BOX (hbox8), image157, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_(" Verteiler"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox8), label13, FALSE, FALSE, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow4, TRUE, TRUE, 0);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), viewport1);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_table_attach (GTK_TABLE (MainTable), statusbar1, 0, 1, 3, 4,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);

  g_signal_connect ((gpointer) MainFrame, "destroy",
		    G_CALLBACK (on_MainFrame_destroy), NULL);
  g_signal_connect ((gpointer) new_project, "activate",
		    G_CALLBACK (on_new_project_activate), NULL);
  g_signal_connect ((gpointer) open_project, "activate",
		    G_CALLBACK (on_open_project_activate), NULL);
  g_signal_connect ((gpointer) Save, "activate",
		    G_CALLBACK (on_Save_activate), NULL);
  g_signal_connect ((gpointer) Save_As, "activate",
		    G_CALLBACK (on_Save_As_activate), NULL);
  g_signal_connect ((gpointer) Quitt, "activate",
		    G_CALLBACK (on_Quitt_activate), NULL);
  g_signal_connect ((gpointer) ShowDeviceData, "activate",
		    G_CALLBACK (on_ShowDeviceData_activate), NULL);
  g_signal_connect ((gpointer) editDeviceData, "activate",
		    G_CALLBACK (on_editDeviceData_activate), NULL);
  g_signal_connect ((gpointer) ConvertDeviceData, "activate",
		    G_CALLBACK (on_ConvertDeviceData_activate), NULL);
  g_signal_connect ((gpointer) ImportXMLDeviceData, "activate",
		    G_CALLBACK (on_ImportXMLDeviceData_activate), NULL);
  g_signal_connect ((gpointer) ExportXMLDeviceData, "activate",
		    G_CALLBACK (on_ExportXMLDeviceData_activate), NULL);
  g_signal_connect ((gpointer) About, "activate",
		    G_CALLBACK (on_About_activate), NULL);
  g_signal_connect ((gpointer) ProjectTree, "drag_data_received",
		    G_CALLBACK (on_ProjectTree_drag_data_received), NULL);
  g_signal_connect ((gpointer) ProjectTree, "drag_motion",
		    G_CALLBACK (on_ProjectTree_drag_motion), NULL);
  g_signal_connect ((gpointer) ProjectTree, "button_press_event",
		    G_CALLBACK (on_ProjectTree_button_press_event), NULL);
  g_signal_connect ((gpointer) button_building, "drag_begin",
		    G_CALLBACK (on_button_building_drag_begin), NULL);
  g_signal_connect ((gpointer) button_building, "drag_data_get",
		    G_CALLBACK (on_button_drag_data_get), NULL);
  g_signal_connect ((gpointer) button_floor, "drag_begin",
		    G_CALLBACK (on_button_floor_drag_begin), NULL);
  g_signal_connect ((gpointer) button_floor, "drag_data_get",
		    G_CALLBACK (on_button_drag_data_get), NULL);
  g_signal_connect ((gpointer) button_room, "drag_begin",
		    G_CALLBACK (on_button_room_drag_begin), NULL);
  g_signal_connect ((gpointer) button_room, "drag_data_get",
		    G_CALLBACK (on_button_drag_data_get), NULL);
  g_signal_connect ((gpointer) button_junction, "drag_begin",
		    G_CALLBACK (on_button_junction_drag_begin), NULL);
  g_signal_connect ((gpointer) button_junction, "drag_data_get",
		    G_CALLBACK (on_button_drag_data_get), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MainFrame, MainFrame, "MainFrame");
  GLADE_HOOKUP_OBJECT (MainFrame, MainTable, "MainTable");
  GLADE_HOOKUP_OBJECT (MainFrame, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (MainFrame, MainMenu, "MainMenu");
  GLADE_HOOKUP_OBJECT (MainFrame, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (MainFrame, image454, "image454");
  GLADE_HOOKUP_OBJECT (MainFrame, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (MainFrame, new_project, "new_project");
  GLADE_HOOKUP_OBJECT (MainFrame, image455, "image455");
  GLADE_HOOKUP_OBJECT (MainFrame, open_project, "open_project");
  GLADE_HOOKUP_OBJECT (MainFrame, image456, "image456");
  GLADE_HOOKUP_OBJECT (MainFrame, Save, "Save");
  GLADE_HOOKUP_OBJECT (MainFrame, image457, "image457");
  GLADE_HOOKUP_OBJECT (MainFrame, Save_As, "Save_As");
  GLADE_HOOKUP_OBJECT (MainFrame, image458, "image458");
  GLADE_HOOKUP_OBJECT (MainFrame, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (MainFrame, Quitt, "Quitt");
  GLADE_HOOKUP_OBJECT (MainFrame, image459, "image459");
  GLADE_HOOKUP_OBJECT (MainFrame, DeviceData, "DeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image460, "image460");
  GLADE_HOOKUP_OBJECT (MainFrame, DeviceData_menu, "DeviceData_menu");
  GLADE_HOOKUP_OBJECT (MainFrame, ShowDeviceData, "ShowDeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image461, "image461");
  GLADE_HOOKUP_OBJECT (MainFrame, editDeviceData, "editDeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image462, "image462");
  GLADE_HOOKUP_OBJECT (MainFrame, ConvertDeviceData, "ConvertDeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image463, "image463");
  GLADE_HOOKUP_OBJECT (MainFrame, ImportXMLDeviceData, "ImportXMLDeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image464, "image464");
  GLADE_HOOKUP_OBJECT (MainFrame, ExportXMLDeviceData, "ExportXMLDeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image465, "image465");
  GLADE_HOOKUP_OBJECT (MainFrame, About, "About");
  GLADE_HOOKUP_OBJECT (MainFrame, image466, "image466");
  GLADE_HOOKUP_OBJECT (MainFrame, PanelLeft, "PanelLeft");
  GLADE_HOOKUP_OBJECT (MainFrame, PanelRight, "PanelRight");
  GLADE_HOOKUP_OBJECT (MainFrame, ScrolledWindowLeft, "ScrolledWindowLeft");
  GLADE_HOOKUP_OBJECT (MainFrame, ProjectTree, "ProjectTree");
  GLADE_HOOKUP_OBJECT (MainFrame, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (MainFrame, handlebox_toolbar, "handlebox_toolbar");
  GLADE_HOOKUP_OBJECT (MainFrame, eventbox_Toolbar, "eventbox_Toolbar");
  GLADE_HOOKUP_OBJECT (MainFrame, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (MainFrame, button_building, "button_building");
  GLADE_HOOKUP_OBJECT (MainFrame, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (MainFrame, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (MainFrame, image154, "image154");
  GLADE_HOOKUP_OBJECT (MainFrame, label10, "label10");
  GLADE_HOOKUP_OBJECT (MainFrame, button_floor, "button_floor");
  GLADE_HOOKUP_OBJECT (MainFrame, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (MainFrame, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (MainFrame, image155, "image155");
  GLADE_HOOKUP_OBJECT (MainFrame, label11, "label11");
  GLADE_HOOKUP_OBJECT (MainFrame, button_room, "button_room");
  GLADE_HOOKUP_OBJECT (MainFrame, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (MainFrame, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (MainFrame, image156, "image156");
  GLADE_HOOKUP_OBJECT (MainFrame, label12, "label12");
  GLADE_HOOKUP_OBJECT (MainFrame, button_junction, "button_junction");
  GLADE_HOOKUP_OBJECT (MainFrame, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (MainFrame, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (MainFrame, image157, "image157");
  GLADE_HOOKUP_OBJECT (MainFrame, label13, "label13");
  GLADE_HOOKUP_OBJECT (MainFrame, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (MainFrame, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (MainFrame, statusbar1, "statusbar1");
  GLADE_HOOKUP_OBJECT_NO_REF (MainFrame, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (MainFrame), accel_group);

  return MainFrame;
}

GtkWidget *
create_New_Project (void)
{
  GtkWidget *New_Project;
  GdkPixbuf *New_Project_icon_pixbuf;
  GtkWidget *dialog_vbox1;
  GtkWidget *table1;
  GtkWidget *label6;
  GtkWidget *editProjectName;
  GtkWidget *FileChooser;
  GtkWidget *checkCreateProjDir;
  GtkWidget *dialog_action_area1;
  GtkWidget *bCancel;
  GtkWidget *alignment2;
  GtkWidget *hbox1;
  GtkWidget *image131;
  GtkWidget *label1;
  GtkWidget *bOK;
  GtkWidget *alignment3;
  GtkWidget *hbox2;
  GtkWidget *image145;
  GtkWidget *label7;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  New_Project = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (New_Project), _("Neues Projekt anlegen"));
  gtk_window_set_position (GTK_WINDOW (New_Project), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (New_Project), TRUE);
  New_Project_icon_pixbuf = create_pixbuf ("document-new.png");
  if (New_Project_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (New_Project), New_Project_icon_pixbuf);
      gdk_pixbuf_unref (New_Project_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (New_Project),
			    GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (New_Project)->vbox;
  gtk_widget_show (dialog_vbox1);
  gtk_widget_set_size_request (dialog_vbox1, 600, 300);

  table1 = gtk_table_new (2, 3, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), table1, TRUE, TRUE, 0);

  label6 = gtk_label_new (_("Projektname:"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label6), 0, 9);

  editProjectName = gtk_entry_new ();
  gtk_widget_show (editProjectName);
  gtk_table_attach (GTK_TABLE (table1), editProjectName, 1, 2, 1, 2,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 0, 6);
  gtk_tooltips_set_tip (tooltips, editProjectName,
			_("Geben Sie hier den Namen des neuen Projektes ein"),
			NULL);
  gtk_entry_set_max_length (GTK_ENTRY (editProjectName), 50);
  gtk_entry_set_text (GTK_ENTRY (editProjectName), _("Neues Projekt"));

  FileChooser =
    gtk_file_chooser_widget_new (GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_show (FileChooser);
  gtk_table_attach (GTK_TABLE (table1), FileChooser, 0, 3, 0, 1,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  checkCreateProjDir =
    gtk_check_button_new_with_mnemonic (_("Projektordner anlegen"));
  gtk_widget_show (checkCreateProjDir);
  gtk_table_attach (GTK_TABLE (table1), checkCreateProjDir, 2, 3, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 20, 0);
  gtk_tooltips_set_tip (tooltips, checkCreateProjDir,
			_
			("erzeugt ein Projektverzeichnis mit dem Namen des Projektes"),
			NULL);

  dialog_action_area1 = GTK_DIALOG (New_Project)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1),
			     GTK_BUTTONBOX_END);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (New_Project), bCancel,
				GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bCancel, _("Schliesst Dialog ohne Aktion"),
			NULL);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment2);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox1);

  image131 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image131);
  gtk_box_pack_start (GTK_BOX (hbox1), image131, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Abbrechen"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  bOK = gtk_button_new ();
  gtk_widget_show (bOK);
  gtk_dialog_add_action_widget (GTK_DIALOG (New_Project), bOK,
				GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (bOK, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bOK,
			_("schliesst Dialog und Ã¼bernimmt die Eingaben"),
			NULL);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (bOK), alignment3);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox2);

  image145 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image145);
  gtk_box_pack_start (GTK_BOX (hbox2), image145, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) New_Project, "close",
		    G_CALLBACK (on_New_Project_close), NULL);
  g_signal_connect ((gpointer) bCancel, "clicked",
		    G_CALLBACK (on_bCancel_clicked), NULL);
  g_signal_connect ((gpointer) bOK, "clicked",
		    G_CALLBACK (on_bOK_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (New_Project, New_Project, "New_Project");
  GLADE_HOOKUP_OBJECT_NO_REF (New_Project, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (New_Project, table1, "table1");
  GLADE_HOOKUP_OBJECT (New_Project, label6, "label6");
  GLADE_HOOKUP_OBJECT (New_Project, editProjectName, "editProjectName");
  GLADE_HOOKUP_OBJECT (New_Project, FileChooser, "FileChooser");
  GLADE_HOOKUP_OBJECT (New_Project, checkCreateProjDir, "checkCreateProjDir");
  GLADE_HOOKUP_OBJECT_NO_REF (New_Project, dialog_action_area1,
			      "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (New_Project, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (New_Project, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (New_Project, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (New_Project, image131, "image131");
  GLADE_HOOKUP_OBJECT (New_Project, label1, "label1");
  GLADE_HOOKUP_OBJECT (New_Project, bOK, "bOK");
  GLADE_HOOKUP_OBJECT (New_Project, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (New_Project, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (New_Project, image145, "image145");
  GLADE_HOOKUP_OBJECT (New_Project, label7, "label7");
  GLADE_HOOKUP_OBJECT_NO_REF (New_Project, tooltips, "tooltips");

  gtk_widget_grab_focus (bOK);
  gtk_widget_grab_default (bOK);
  return New_Project;
}

GtkWidget *
create_Open_Project (void)
{
  GtkWidget *Open_Project;
  GdkPixbuf *Open_Project_icon_pixbuf;
  GtkWidget *FileChooser;
  GtkWidget *dialog_action_area2;
  GtkWidget *bCancel;
  GtkWidget *alignment5;
  GtkWidget *hbox4;
  GtkWidget *image147;
  GtkWidget *label9;
  GtkWidget *bOK;
  GtkWidget *alignment4;
  GtkWidget *hbox3;
  GtkWidget *image146;
  GtkWidget *label8;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  Open_Project =
    gtk_file_chooser_dialog_new (_("Ã\226ffne vorhandenes Projekt"), NULL,
				 GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_position (GTK_WINDOW (Open_Project), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (Open_Project), TRUE);
  Open_Project_icon_pixbuf = create_pixbuf ("document-open.png");
  if (Open_Project_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (Open_Project),
			   Open_Project_icon_pixbuf);
      gdk_pixbuf_unref (Open_Project_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (Open_Project),
			    GDK_WINDOW_TYPE_HINT_DIALOG);

  FileChooser = GTK_DIALOG (Open_Project)->vbox;
  gtk_widget_show (FileChooser);

  dialog_action_area2 = GTK_DIALOG (Open_Project)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2),
			     GTK_BUTTONBOX_END);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (Open_Project), bCancel,
				GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bCancel, _("Schliesst Dialog ohne Aktion"),
			NULL);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment5);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox4);

  image147 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image147);
  gtk_box_pack_start (GTK_BOX (hbox4), image147, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Abbrechen"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  bOK = gtk_button_new ();
  gtk_widget_show (bOK);
  gtk_dialog_add_action_widget (GTK_DIALOG (Open_Project), bOK,
				GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (bOK, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bOK,
			_("schliesst Dialog und Ã¼bernimmt die Eingaben"),
			NULL);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (bOK), alignment4);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox3);

  image146 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image146);
  gtk_box_pack_start (GTK_BOX (hbox3), image146, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) Open_Project, "destroy",
		    G_CALLBACK (on_Open_Project_destroy), NULL);
  g_signal_connect ((gpointer) bCancel, "clicked",
		    G_CALLBACK (on_bCancel_clicked), NULL);
  g_signal_connect ((gpointer) bOK, "clicked",
		    G_CALLBACK (on_bOK_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Open_Project, Open_Project, "Open_Project");
  GLADE_HOOKUP_OBJECT_NO_REF (Open_Project, FileChooser, "FileChooser");
  GLADE_HOOKUP_OBJECT_NO_REF (Open_Project, dialog_action_area2,
			      "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (Open_Project, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (Open_Project, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Open_Project, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Open_Project, image147, "image147");
  GLADE_HOOKUP_OBJECT (Open_Project, label9, "label9");
  GLADE_HOOKUP_OBJECT (Open_Project, bOK, "bOK");
  GLADE_HOOKUP_OBJECT (Open_Project, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Open_Project, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Open_Project, image146, "image146");
  GLADE_HOOKUP_OBJECT (Open_Project, label8, "label8");
  GLADE_HOOKUP_OBJECT_NO_REF (Open_Project, tooltips, "tooltips");

  gtk_widget_grab_default (bOK);
  return Open_Project;
}

GtkWidget *
create_mnuPopupTree (void)
{
  GtkWidget *mnuPopupTree;
  GtkWidget *mnuChangeName;
  GtkWidget *image199;
  GtkWidget *mnuDeleteGroup;
  GtkWidget *image200;
  GtkWidget *separator1;
  GtkWidget *mnuPropertyGroup;
  GtkWidget *image201;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  mnuPopupTree = gtk_menu_new ();

  mnuChangeName = gtk_image_menu_item_new_with_mnemonic (_("Umbenennen"));
  gtk_widget_show (mnuChangeName);
  gtk_container_add (GTK_CONTAINER (mnuPopupTree), mnuChangeName);
  gtk_tooltips_set_tip (tooltips, mnuChangeName,
			_("zum editieren des Namens"), NULL);

  image199 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image199);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (mnuChangeName),
				 image199);

  mnuDeleteGroup = gtk_image_menu_item_new_with_mnemonic (_("LÃ\266schen"));
  gtk_widget_show (mnuDeleteGroup);
  gtk_container_add (GTK_CONTAINER (mnuPopupTree), mnuDeleteGroup);
  gtk_tooltips_set_tip (tooltips, mnuDeleteGroup,
			_("lÃ\266scht diese Gruppe"), NULL);

  image200 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image200);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (mnuDeleteGroup),
				 image200);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (mnuPopupTree), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  mnuPropertyGroup =
    gtk_image_menu_item_new_with_mnemonic (_("Eigenschaften"));
  gtk_widget_show (mnuPropertyGroup);
  gtk_container_add (GTK_CONTAINER (mnuPopupTree), mnuPropertyGroup);
  gtk_tooltips_set_tip (tooltips, mnuPropertyGroup,
			_("zeigt die Eigenschaften dieser Gruppe an"), NULL);

  image201 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image201);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (mnuPropertyGroup),
				 image201);

  g_signal_connect ((gpointer) mnuPopupTree, "button_press_event",
		    G_CALLBACK (on_mnuPopupTree_button_press_event), NULL);
  g_signal_connect ((gpointer) mnuPopupTree, "key_press_event",
		    G_CALLBACK (on_mnuPopupTree_key_press_event), NULL);
  g_signal_connect ((gpointer) mnuChangeName, "activate",
		    G_CALLBACK (on_mnuChangeName_activate), NULL);
  g_signal_connect ((gpointer) mnuDeleteGroup, "activate",
		    G_CALLBACK (on_mnuDeleteGroup_activate), NULL);
  g_signal_connect ((gpointer) mnuPropertyGroup, "activate",
		    G_CALLBACK (on_mnuPropertyGroup_activate), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mnuPopupTree, mnuPopupTree, "mnuPopupTree");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, mnuChangeName, "mnuChangeName");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, image199, "image199");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, mnuDeleteGroup, "mnuDeleteGroup");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, image200, "image200");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, mnuPropertyGroup, "mnuPropertyGroup");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, image201, "image201");
  GLADE_HOOKUP_OBJECT_NO_REF (mnuPopupTree, tooltips, "tooltips");

  return mnuPopupTree;
}

GtkWidget *
create_DlgAddStructureElement (void)
{
  GtkWidget *DlgAddStructureElement;
  GtkWidget *dialog_vbox2;
  GtkWidget *table2;
  GtkWidget *lblText;
  GtkWidget *txtElementName;
  GtkWidget *dialog_action_area3;
  GtkWidget *bCancel;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image202;
  GtkWidget *label15;
  GtkWidget *bOK;
  GtkWidget *alignment11;
  GtkWidget *hbox10;
  GtkWidget *image203;
  GtkWidget *label16;

  DlgAddStructureElement = gtk_dialog_new ();
  gtk_widget_set_size_request (DlgAddStructureElement, 425, 112);
  gtk_window_set_title (GTK_WINDOW (DlgAddStructureElement),
			_("Name des neuen Strukturelementes"));
  gtk_window_set_position (GTK_WINDOW (DlgAddStructureElement),
			   GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (DlgAddStructureElement), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (DlgAddStructureElement), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (DlgAddStructureElement),
				      TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (DlgAddStructureElement),
			    GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (DlgAddStructureElement)->vbox;
  gtk_widget_show (dialog_vbox2);

  table2 = gtk_table_new (2, 1, FALSE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), table2, TRUE, TRUE, 0);

  lblText =
    gtk_label_new (_("Wie mÃ\266chten Sie das neue Element benennen ?"));
  gtk_widget_show (lblText);
  gtk_table_attach (GTK_TABLE (table2), lblText, 0, 1, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblText), 0.06, 0.5);
  gtk_misc_set_padding (GTK_MISC (lblText), 0, 10);

  txtElementName = gtk_entry_new ();
  gtk_widget_show (txtElementName);
  gtk_table_attach (GTK_TABLE (table2), txtElementName, 0, 1, 1, 2,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 5, 0);
  gtk_entry_set_max_length (GTK_ENTRY (txtElementName), 100);

  dialog_action_area3 = GTK_DIALOG (DlgAddStructureElement)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3),
			     GTK_BUTTONBOX_END);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgAddStructureElement), bCancel,
				GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image202 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image202);
  gtk_box_pack_start (GTK_BOX (hbox9), image202, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("_Abbrechen"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox9), label15, FALSE, FALSE, 0);

  bOK = gtk_button_new ();
  gtk_widget_show (bOK);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgAddStructureElement), bOK,
				GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (bOK, GTK_CAN_DEFAULT);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (bOK), alignment11);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox10);

  image203 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image203);
  gtk_box_pack_start (GTK_BOX (hbox10), image203, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Ã\234_bernehmen"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox10), label16, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) DlgAddStructureElement, "destroy",
		    G_CALLBACK (on_DlgAddStructureElement_destroy), NULL);
  g_signal_connect ((gpointer) DlgAddStructureElement, "response",
		    G_CALLBACK (on_DlgAddStructureElement_response), NULL);
  g_signal_connect ((gpointer) bCancel, "clicked",
		    G_CALLBACK (on_bCancel_clicked), NULL);
  g_signal_connect ((gpointer) bOK, "clicked",
		    G_CALLBACK (on_bOK_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (DlgAddStructureElement, DlgAddStructureElement,
			      "DlgAddStructureElement");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgAddStructureElement, dialog_vbox2,
			      "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, table2, "table2");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, lblText, "lblText");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, txtElementName,
		       "txtElementName");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgAddStructureElement, dialog_action_area3,
			      "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, image202, "image202");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, label15, "label15");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, bOK, "bOK");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, image203, "image203");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, label16, "label16");

  return DlgAddStructureElement;
}

GtkWidget *
create_DlgConvertDeviceData (void)
{
  GtkWidget *DlgConvertDeviceData;
  GdkPixbuf *DlgConvertDeviceData_icon_pixbuf;
  GtkWidget *dialog_vbox3;
  GtkWidget *table3;
  GtkWidget *txtSourceFile;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *bSelect;
  GtkWidget *ConvertProgress;
  GtkWidget *alignment14;
  GtkWidget *txtDestFile;
  GtkWidget *dialog_action_area4;
  GtkWidget *bCancel;
  GtkWidget *alignment17;
  GtkWidget *hbox15;
  GtkWidget *image471;
  GtkWidget *label23;
  GtkWidget *bConvert;
  GtkWidget *alignment12;
  GtkWidget *hbox11;
  GtkWidget *image467;
  GtkWidget *label17;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  DlgConvertDeviceData = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (DlgConvertDeviceData),
			_("Stammdaten Konverter"));
  gtk_window_set_position (GTK_WINDOW (DlgConvertDeviceData),
			   GTK_WIN_POS_CENTER);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (DlgConvertDeviceData),
				      TRUE);
  DlgConvertDeviceData_icon_pixbuf = create_pixbuf ("converter_icon.png");
  if (DlgConvertDeviceData_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (DlgConvertDeviceData),
			   DlgConvertDeviceData_icon_pixbuf);
      gdk_pixbuf_unref (DlgConvertDeviceData_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (DlgConvertDeviceData),
			    GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (DlgConvertDeviceData)->vbox;
  gtk_widget_show (dialog_vbox3);

  table3 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), table3, TRUE, TRUE, 0);

  txtSourceFile = gtk_entry_new ();
  gtk_widget_show (txtSourceFile);
  gtk_table_attach (GTK_TABLE (table3), txtSourceFile, 1, 2, 0, 1,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, txtSourceFile,
			_
			("WÃ¤hlen Sie hier die zu konvertierende *._vd Datei aus. "),
			NULL);

  label20 = gtk_label_new (_("Name der Zieldatei:"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table3), label20, 0, 1, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label19 = gtk_label_new (_("zu konvertierende Datei auswÃ¤hlen:"));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table3), label19, 0, 1, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 11);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  bSelect = gtk_button_new_with_mnemonic (_("Durchsuchen..."));
  gtk_widget_show (bSelect);
  gtk_table_attach (GTK_TABLE (table3), bSelect, 2, 3, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 7, 0);
  gtk_tooltips_set_tip (tooltips, bSelect,
			_("Ã\266ffnet den Dateiauswahldialog"), NULL);

  ConvertProgress = gtk_progress_bar_new ();
  gtk_widget_show (ConvertProgress);
  gtk_table_attach (GTK_TABLE (table3), ConvertProgress, 0, 3, 2, 3,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 14);
  gtk_progress_bar_set_pulse_step (GTK_PROGRESS_BAR (ConvertProgress), 0);

  alignment14 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment14);
  gtk_table_attach (GTK_TABLE (table3), alignment14, 1, 3, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment14), 0, 0, 0, 260);

  txtDestFile = gtk_entry_new ();
  gtk_widget_show (txtDestFile);
  gtk_container_add (GTK_CONTAINER (alignment14), txtDestFile);
  gtk_tooltips_set_tip (tooltips, txtDestFile,
			_
			("Geben Sie hier den Namen der konvertierten Datei ein. Ein Dateierweiterung ist nicht notwendig."),
			NULL);
  gtk_entry_set_max_length (GTK_ENTRY (txtDestFile), 30);

  dialog_action_area4 = GTK_DIALOG (DlgConvertDeviceData)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4),
			     GTK_BUTTONBOX_END);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgConvertDeviceData), bCancel,
				GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bCancel,
			_("beendet den Konverter und schlieÃŸt den Dialog"),
			NULL);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment17);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox15);

  image471 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image471);
  gtk_box_pack_start (GTK_BOX (hbox15), image471, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("SchlieÃŸen"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox15), label23, FALSE, FALSE, 0);

  bConvert = gtk_button_new ();
  gtk_widget_show (bConvert);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgConvertDeviceData), bConvert,
				0);
  GTK_WIDGET_SET_FLAGS (bConvert, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bConvert,
			_("startet den Konvertierungsvorgang"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (bConvert), FALSE);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (bConvert), alignment12);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox11);

  image467 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image467);
  gtk_box_pack_start (GTK_BOX (hbox11), image467, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Konvertieren"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox11), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bSelect, "clicked",
		    G_CALLBACK (on_bSelect_clicked), NULL);
  g_signal_connect ((gpointer) bCancel, "clicked",
		    G_CALLBACK (on_bCancel_clicked), NULL);
  g_signal_connect ((gpointer) bConvert, "clicked",
		    G_CALLBACK (on_bConvert_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (DlgConvertDeviceData, DlgConvertDeviceData,
			      "DlgConvertDeviceData");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgConvertDeviceData, dialog_vbox3,
			      "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, table3, "table3");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, txtSourceFile, "txtSourceFile");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, label20, "label20");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, label19, "label19");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, bSelect, "bSelect");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, ConvertProgress,
		       "ConvertProgress");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, txtDestFile, "txtDestFile");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgConvertDeviceData, dialog_action_area4,
			      "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, image471, "image471");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, label23, "label23");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, bConvert, "bConvert");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, image467, "image467");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, label17, "label17");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgConvertDeviceData, tooltips, "tooltips");

  return DlgConvertDeviceData;
}

GtkWidget *
create_DlgFileChooser (void)
{
  GtkWidget *DlgFileChooser;
  GdkPixbuf *DlgFileChooser_icon_pixbuf;
  GtkWidget *dialog_vbox4;
  GtkWidget *dialog_action_area5;
  GtkWidget *bCancel;
  GtkWidget *alignment16;
  GtkWidget *hbox14;
  GtkWidget *image470;
  GtkWidget *label22;
  GtkWidget *bApply;
  GtkWidget *alignment15;
  GtkWidget *hbox13;
  GtkWidget *image469;
  GtkWidget *label21;

  DlgFileChooser =
    gtk_file_chooser_dialog_new (_("Datei auswÃ¤hlen..."), NULL,
				 GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_modal (GTK_WINDOW (DlgFileChooser), TRUE);
  DlgFileChooser_icon_pixbuf = create_pixbuf ("document-open.png");
  if (DlgFileChooser_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (DlgFileChooser),
			   DlgFileChooser_icon_pixbuf);
      gdk_pixbuf_unref (DlgFileChooser_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (DlgFileChooser),
			    GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox4 = GTK_DIALOG (DlgFileChooser)->vbox;
  gtk_widget_show (dialog_vbox4);

  dialog_action_area5 = GTK_DIALOG (DlgFileChooser)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5),
			     GTK_BUTTONBOX_END);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgFileChooser), bCancel,
				GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment16);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox14);

  image470 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image470);
  gtk_box_pack_start (GTK_BOX (hbox14), image470, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Abbrechen"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox14), label22, FALSE, FALSE, 0);

  bApply = gtk_button_new ();
  gtk_widget_show (bApply);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgFileChooser), bApply,
				GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (bApply, GTK_CAN_DEFAULT);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (bApply), alignment15);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox13);

  image469 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image469);
  gtk_box_pack_start (GTK_BOX (hbox13), image469, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Ã\234bernehmen"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox13), label21, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (DlgFileChooser, DlgFileChooser,
			      "DlgFileChooser");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgFileChooser, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgFileChooser, dialog_action_area5,
			      "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, image470, "image470");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, label22, "label22");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, bApply, "bApply");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, image469, "image469");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, label21, "label21");

  gtk_widget_grab_default (bApply);
  return DlgFileChooser;
}
