/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget *create_MainFrame (void);
GtkWidget *create_New_Project (void);
GtkWidget *create_Open_Project (void);
GtkWidget *create_mnuPopupTree (void);
GtkWidget *create_DlgAddStructureElement (void);
GtkWidget *create_DlgConvertDeviceData (void);
GtkWidget *create_DlgFileChooser (void);
