/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget *
create_MainFrame (void)
{
  GtkWidget *MainFrame;
  GdkPixbuf *MainFrame_icon_pixbuf;
  GtkWidget *MainTable;
  GtkWidget *alignment1;
  GtkWidget *MainMenu;
  GtkWidget *menuitem1;
  GtkWidget *image454;
  GtkWidget *menuitem1_menu;
  GtkWidget *new_project;
  GtkWidget *image455;
  GtkWidget *open_project;
  GtkWidget *image456;
  GtkWidget *Save;
  GtkWidget *image457;
  GtkWidget *Save_As;
  GtkWidget *image458;
  GtkWidget *separatormenuitem1;
  GtkWidget *Quitt;
  GtkWidget *image459;
  GtkWidget *DeviceData;
  GtkWidget *image460;
  GtkWidget *DeviceData_menu;
  GtkWidget *ShowDeviceData;
  GtkWidget *image461;
  GtkWidget *editDeviceData;
  GtkWidget *image462;
  GtkWidget *ConvertDeviceData;
  GtkWidget *image463;
  GtkWidget *ImportXMLDeviceData;
  GtkWidget *image464;
  GtkWidget *ExportXMLDeviceData;
  GtkWidget *image465;
  GtkWidget *About;
  GtkWidget *image466;
  GtkWidget *statusbar1;
  GtkWidget *PanelLeft;
  GtkWidget *PanelRight;
  GtkWidget *ScrolledWindowLeft;
  GtkWidget *ProjectTree;
  GtkWidget *vbox1;
  GtkWidget *handlebox_toolbar;
  GtkWidget *eventbox_Toolbar;
  GtkWidget *hbuttonbox1;
  GtkWidget *button_building;
  GtkWidget *alignment6;
  GtkWidget *hbox5;
  GtkWidget *image154;
  GtkWidget *label10;
  GtkWidget *button_floor;
  GtkWidget *alignment7;
  GtkWidget *hbox6;
  GtkWidget *image155;
  GtkWidget *label11;
  GtkWidget *button_room;
  GtkWidget *alignment8;
  GtkWidget *hbox7;
  GtkWidget *image156;
  GtkWidget *label12;
  GtkWidget *button_junction;
  GtkWidget *alignment9;
  GtkWidget *hbox8;
  GtkWidget *image157;
  GtkWidget *label13;
  GtkWidget *scrolledwindow4;
  GtkWidget *viewport1;
  GtkWidget *vpaned2;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow12;
  GtkWidget *viewport3;
  GtkWidget *scrolledwindow13;
  GtkWidget *textview1;
  GtkWidget *label47;
  GtkWidget *empty_notebook_page;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *hpaned2;
  GtkWidget *vboxGroupAddress;
  GtkWidget *label57;
  GtkWidget *scrolledwindowGroupAddress;
  GtkWidget *GroupAddressTree;
  GtkWidget *vboxTopology;
  GtkWidget *label58;
  GtkWidget *scrolledwindowTopology;
  GtkWidget *TopologyTree;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  MainFrame = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (MainFrame, 1200, 980);
  gtk_window_set_title (GTK_WINDOW (MainFrame), _("Freebus-ETS"));
  gtk_window_set_position (GTK_WINDOW (MainFrame), GTK_WIN_POS_CENTER);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (MainFrame), TRUE);
  MainFrame_icon_pixbuf = create_pixbuf ("freebuslq5.png");
  if (MainFrame_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (MainFrame), MainFrame_icon_pixbuf);
      gdk_pixbuf_unref (MainFrame_icon_pixbuf);
    }

  MainTable = gtk_table_new (4, 1, FALSE);
  gtk_widget_show (MainTable);
  gtk_container_add (GTK_CONTAINER (MainFrame), MainTable);

  alignment1 = gtk_alignment_new (0, 0, 1, 0);
  gtk_widget_show (alignment1);
  gtk_table_attach (GTK_TABLE (MainTable), alignment1, 0, 1, 0, 1,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (GTK_FILL), 0, 0);

  MainMenu = gtk_menu_bar_new ();
  gtk_widget_show (MainMenu);
  gtk_container_add (GTK_CONTAINER (alignment1), MainMenu);

  menuitem1 = gtk_image_menu_item_new_with_mnemonic (_("_Datei"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (MainMenu), menuitem1);

  image454 = create_pixmap (MainFrame, "file-manager.png");
  gtk_widget_show (image454);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (menuitem1), image454);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  new_project = gtk_image_menu_item_new_with_mnemonic (_("_Neues Projekt"));
  gtk_widget_show (new_project);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), new_project);
  gtk_tooltips_set_tip (tooltips, new_project, _("erzeugt ein neues Projekt"),
			NULL);
  gtk_widget_add_accelerator (new_project, "activate", accel_group, GDK_N,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image455 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image455);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (new_project), image455);

  open_project =
    gtk_image_menu_item_new_with_mnemonic (_("�\226ffne Pr_ojekt"));
  gtk_widget_show (open_project);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), open_project);
  gtk_tooltips_set_tip (tooltips, open_project,
			_("�\266ffnet ein vorhandenes Projekt"), NULL);
  gtk_widget_add_accelerator (open_project, "activate", accel_group, GDK_O,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image456 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image456);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (open_project),
				 image456);

  Save = gtk_image_menu_item_new_with_mnemonic (_("_Speichern"));
  gtk_widget_show (Save);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), Save);
  gtk_tooltips_set_tip (tooltips, Save,
			_("speichert Projekt unter aktuellen Namen"), NULL);
  gtk_widget_add_accelerator (Save, "activate", accel_group, GDK_S,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image457 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image457);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (Save), image457);

  Save_As = gtk_image_menu_item_new_with_mnemonic (_("S_peichern unter"));
  gtk_widget_show (Save_As);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), Save_As);
  gtk_tooltips_set_tip (tooltips, Save_As,
			_("speichert das Projekt unter einem neuen Namen"),
			NULL);
  gtk_widget_add_accelerator (Save_As, "activate", accel_group, GDK_S,
			      GDK_CONTROL_MASK | GDK_SHIFT_MASK,
			      GTK_ACCEL_VISIBLE);

  image458 = gtk_image_new_from_stock ("gtk-save-as", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image458);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (Save_As), image458);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  Quitt = gtk_image_menu_item_new_with_mnemonic (_("_Beenden"));
  gtk_widget_show (Quitt);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), Quitt);
  gtk_tooltips_set_tip (tooltips, Quitt, _("beendet das sch�\266ne Programm"),
			NULL);
  gtk_widget_add_accelerator (Quitt, "activate", accel_group, GDK_Q,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image459 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image459);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (Quitt), image459);

  DeviceData = gtk_image_menu_item_new_with_mnemonic (_("_Gerätedaten"));
  gtk_widget_show (DeviceData);
  gtk_container_add (GTK_CONTAINER (MainMenu), DeviceData);

  image460 = create_pixmap (MainFrame, "package-x-generic.png");
  gtk_widget_show (image460);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (DeviceData), image460);

  DeviceData_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (DeviceData), DeviceData_menu);

  ShowDeviceData = gtk_image_menu_item_new_with_mnemonic (_("_Anzeigen"));
  gtk_widget_show (ShowDeviceData);
  gtk_container_add (GTK_CONTAINER (DeviceData_menu), ShowDeviceData);
  gtk_tooltips_set_tip (tooltips, ShowDeviceData,
			_
			("zeigt die im Projekt verfügbaren Gerätestammdaten an"),
			NULL);
  gtk_widget_add_accelerator (ShowDeviceData, "activate", accel_group, GDK_A,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image461 = create_pixmap (MainFrame, "show_DeviceData.png");
  gtk_widget_show (image461);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (ShowDeviceData),
				 image461);

  editDeviceData = gtk_image_menu_item_new_with_mnemonic (_("_Bearbeiten"));
  gtk_widget_show (editDeviceData);
  gtk_container_add (GTK_CONTAINER (DeviceData_menu), editDeviceData);
  gtk_tooltips_set_tip (tooltips, editDeviceData,
			_("erstellen und bearbeiten von Gerätestammdaten"),
			NULL);
  gtk_widget_add_accelerator (editDeviceData, "activate", accel_group, GDK_B,
			      GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image462 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image462);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (editDeviceData),
				 image462);

  ConvertDeviceData =
    gtk_image_menu_item_new_with_mnemonic (_("_Konvertieren"));
  gtk_widget_show (ConvertDeviceData);
  gtk_container_add (GTK_CONTAINER (DeviceData_menu), ConvertDeviceData);
  gtk_tooltips_set_tip (tooltips, ConvertDeviceData,
			_
			("Konvertiert vorhandene *.vd_ Dateien in ein XML Format"),
			NULL);
  gtk_widget_add_accelerator (ConvertDeviceData, "activate", accel_group,
			      GDK_K, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image463 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image463);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (ConvertDeviceData),
				 image463);

  ImportXMLDeviceData =
    gtk_image_menu_item_new_with_mnemonic (_("_Import von XML"));
  gtk_widget_show (ImportXMLDeviceData);
  gtk_container_add (GTK_CONTAINER (DeviceData_menu), ImportXMLDeviceData);
  gtk_tooltips_set_tip (tooltips, ImportXMLDeviceData,
			_
			("importiert Gerätedaten aus einer XML-Datei in die Datenbank"),
			NULL);
  gtk_widget_add_accelerator (ImportXMLDeviceData, "activate", accel_group,
			      GDK_I, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image464 =
    gtk_image_new_from_stock ("gtk-media-rewind", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image464);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (ImportXMLDeviceData),
				 image464);

  ExportXMLDeviceData =
    gtk_image_menu_item_new_with_mnemonic (_("_Export nach XML"));
  gtk_widget_show (ExportXMLDeviceData);
  gtk_container_add (GTK_CONTAINER (DeviceData_menu), ExportXMLDeviceData);
  gtk_tooltips_set_tip (tooltips, ExportXMLDeviceData,
			_("exportiert Gerätestammdaten in eine XML-Datei"),
			NULL);
  gtk_widget_add_accelerator (ExportXMLDeviceData, "activate", accel_group,
			      GDK_E, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  image465 =
    gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image465);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (ExportXMLDeviceData),
				 image465);

  About = gtk_image_menu_item_new_with_mnemonic (_("�\234_ber..."));
  gtk_widget_show (About);
  gtk_container_add (GTK_CONTAINER (MainMenu), About);

  image466 = create_pixmap (MainFrame, "dialog-information.png");
  gtk_widget_show (image466);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (About), image466);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_table_attach (GTK_TABLE (MainTable), statusbar1, 0, 1, 3, 4,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);

  PanelLeft = gtk_hpaned_new ();
  gtk_widget_show (PanelLeft);
  gtk_table_attach (GTK_TABLE (MainTable), PanelLeft, 0, 1, 1, 3,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_paned_set_position (GTK_PANED (PanelLeft), 0);

  PanelRight = gtk_hpaned_new ();
  gtk_widget_show (PanelRight);
  gtk_paned_pack2 (GTK_PANED (PanelLeft), PanelRight, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (PanelRight), 260);

  ScrolledWindowLeft = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (ScrolledWindowLeft);
  gtk_paned_pack1 (GTK_PANED (PanelRight), ScrolledWindowLeft, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (ScrolledWindowLeft),
				  GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW
				       (ScrolledWindowLeft),
				       GTK_SHADOW_ETCHED_IN);

  ProjectTree = gtk_tree_view_new ();
  gtk_widget_show (ProjectTree);
  gtk_container_add (GTK_CONTAINER (ScrolledWindowLeft), ProjectTree);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_paned_pack2 (GTK_PANED (PanelRight), vbox1, TRUE, TRUE);

  handlebox_toolbar = gtk_handle_box_new ();
  gtk_widget_show (handlebox_toolbar);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox_toolbar, FALSE, FALSE, 3);
  gtk_handle_box_set_shadow_type (GTK_HANDLE_BOX (handlebox_toolbar),
				  GTK_SHADOW_NONE);

  eventbox_Toolbar = gtk_event_box_new ();
  gtk_widget_show (eventbox_Toolbar);
  gtk_container_add (GTK_CONTAINER (handlebox_toolbar), eventbox_Toolbar);
  gtk_widget_set_events (eventbox_Toolbar, GDK_BUTTON_PRESS_MASK);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_container_add (GTK_CONTAINER (eventbox_Toolbar), hbuttonbox1);
  gtk_widget_set_size_request (hbuttonbox1, -1, 45);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1),
			     GTK_BUTTONBOX_START);

  button_building = gtk_button_new ();
  gtk_widget_show (button_building);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_building);
  gtk_widget_set_size_request (button_building, -1, 40);
  GTK_WIDGET_SET_FLAGS (button_building, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_building,
			_("Füge ein Gebäude hinzu"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button_building), GTK_RELIEF_NONE);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_building), alignment6);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox5);

  image154 = create_pixmap (MainFrame, "building.png");
  gtk_widget_show (image154);
  gtk_box_pack_start (GTK_BOX (hbox5), image154, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_(" Gebäude"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  button_floor = gtk_button_new ();
  gtk_widget_show (button_floor);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_floor);
  gtk_widget_set_size_request (button_floor, -1, 40);
  GTK_WIDGET_SET_FLAGS (button_floor, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_floor, _("Füge eine Etage hinzu"),
			NULL);
  gtk_button_set_relief (GTK_BUTTON (button_floor), GTK_RELIEF_NONE);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_floor), alignment7);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox6);

  image155 = create_pixmap (MainFrame, "floor.png");
  gtk_widget_show (image155);
  gtk_box_pack_start (GTK_BOX (hbox6), image155, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_(" Etage"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox6), label11, FALSE, FALSE, 0);

  button_room = gtk_button_new ();
  gtk_widget_show (button_room);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_room);
  gtk_widget_set_size_request (button_room, -1, 40);
  GTK_WIDGET_SET_FLAGS (button_room, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_room, _("füge einen Raum hinzu"),
			NULL);
  gtk_button_set_relief (GTK_BUTTON (button_room), GTK_RELIEF_NONE);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_room), alignment8);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox7);

  image156 = create_pixmap (MainFrame, "room.png");
  gtk_widget_show (image156);
  gtk_box_pack_start (GTK_BOX (hbox7), image156, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_(" Raum"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox7), label12, FALSE, FALSE, 0);

  button_junction = gtk_button_new ();
  gtk_widget_show (button_junction);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_junction);
  gtk_widget_set_size_request (button_junction, -1, 40);
  GTK_WIDGET_SET_FLAGS (button_junction, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_junction,
			_("füge eine Verteiler hnizu"), NULL);
  gtk_button_set_relief (GTK_BUTTON (button_junction), GTK_RELIEF_NONE);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_junction), alignment9);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox8);

  image157 = create_pixmap (MainFrame, "junctionbox.png");
  gtk_widget_show (image157);
  gtk_box_pack_start (GTK_BOX (hbox8), image157, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_(" Verteiler"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox8), label13, FALSE, FALSE, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), viewport1);

  vpaned2 = gtk_vpaned_new ();
  gtk_widget_show (vpaned2);
  gtk_container_add (GTK_CONTAINER (viewport1), vpaned2);
  gtk_paned_set_position (GTK_PANED (vpaned2), 600);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_paned_pack1 (GTK_PANED (vpaned2), notebook1, TRUE, TRUE);
  gtk_widget_set_size_request (notebook1, -1, 240);

  scrolledwindow12 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow12);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow12);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow12),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport3 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow12), viewport3);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport3),
				GTK_SHADOW_ETCHED_IN);

  scrolledwindow13 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow13);
  gtk_container_add (GTK_CONTAINER (viewport3), scrolledwindow13);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow13),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow13), textview1);

  label47 = gtk_label_new (_("label47"));
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1),
			      gtk_notebook_get_nth_page (GTK_NOTEBOOK
							 (notebook1), 0),
			      label47);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label48 = gtk_label_new (_("label48"));
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1),
			      gtk_notebook_get_nth_page (GTK_NOTEBOOK
							 (notebook1), 1),
			      label48);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label49 = gtk_label_new (_("label49"));
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1),
			      gtk_notebook_get_nth_page (GTK_NOTEBOOK
							 (notebook1), 2),
			      label49);

  hpaned2 = gtk_hpaned_new ();
  gtk_widget_show (hpaned2);
  gtk_paned_pack2 (GTK_PANED (vpaned2), hpaned2, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (hpaned2), 420);

  vboxGroupAddress = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vboxGroupAddress);
  gtk_paned_pack1 (GTK_PANED (hpaned2), vboxGroupAddress, FALSE, TRUE);

  label57 = gtk_label_new (_("<b>Gruppenadressen</b>"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (vboxGroupAddress), label57, FALSE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label57), 0, 1);
  gtk_misc_set_padding (GTK_MISC (label57), 5, 2);

  scrolledwindowGroupAddress = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindowGroupAddress);
  gtk_box_pack_start (GTK_BOX (vboxGroupAddress), scrolledwindowGroupAddress,
		      TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindowGroupAddress, 0, -1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW
				  (scrolledwindowGroupAddress),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW
				       (scrolledwindowGroupAddress),
				       GTK_SHADOW_ETCHED_IN);

  GroupAddressTree = gtk_tree_view_new ();
  gtk_widget_show (GroupAddressTree);
  gtk_container_add (GTK_CONTAINER (scrolledwindowGroupAddress),
		     GroupAddressTree);
  gtk_tooltips_set_tip (tooltips, GroupAddressTree, _("Gruppenadressen"),
			NULL);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (GroupAddressTree), FALSE);

  vboxTopology = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vboxTopology);
  gtk_paned_pack2 (GTK_PANED (hpaned2), vboxTopology, TRUE, FALSE);

  label58 = gtk_label_new (_("<b>Topologie</b>"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (vboxTopology), label58, FALSE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label58), 0, 1);
  gtk_misc_set_padding (GTK_MISC (label58), 5, 2);

  scrolledwindowTopology = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindowTopology);
  gtk_box_pack_start (GTK_BOX (vboxTopology), scrolledwindowTopology, TRUE,
		      TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW
				  (scrolledwindowTopology),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW
				       (scrolledwindowTopology),
				       GTK_SHADOW_ETCHED_IN);

  TopologyTree = gtk_tree_view_new ();
  gtk_widget_show (TopologyTree);
  gtk_container_add (GTK_CONTAINER (scrolledwindowTopology), TopologyTree);
  gtk_tooltips_set_tip (tooltips, TopologyTree, _("Topologie "), NULL);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (TopologyTree), FALSE);

  g_signal_connect ((gpointer) MainFrame, "destroy",
		    G_CALLBACK (on_MainFrame_destroy), NULL);
  g_signal_connect ((gpointer) new_project, "activate",
		    G_CALLBACK (on_new_project_activate), NULL);
  g_signal_connect ((gpointer) open_project, "activate",
		    G_CALLBACK (on_open_project_activate), NULL);
  g_signal_connect ((gpointer) Save, "activate",
		    G_CALLBACK (on_Save_activate), NULL);
  g_signal_connect ((gpointer) Save_As, "activate",
		    G_CALLBACK (on_Save_As_activate), NULL);
  g_signal_connect ((gpointer) Quitt, "activate",
		    G_CALLBACK (on_Quitt_activate), NULL);
  g_signal_connect ((gpointer) ShowDeviceData, "activate",
		    G_CALLBACK (on_ShowDeviceData_activate), NULL);
  g_signal_connect ((gpointer) editDeviceData, "activate",
		    G_CALLBACK (on_editDeviceData_activate), NULL);
  g_signal_connect ((gpointer) ConvertDeviceData, "activate",
		    G_CALLBACK (on_ConvertDeviceData_activate), NULL);
  g_signal_connect ((gpointer) ImportXMLDeviceData, "activate",
		    G_CALLBACK (on_ImportXMLDeviceData_activate), NULL);
  g_signal_connect ((gpointer) ExportXMLDeviceData, "activate",
		    G_CALLBACK (on_ExportXMLDeviceData_activate), NULL);
  g_signal_connect ((gpointer) About, "activate",
		    G_CALLBACK (on_About_activate), NULL);
  g_signal_connect ((gpointer) ProjectTree, "drag_data_received",
		    G_CALLBACK (on_ProjectTree_drag_data_received), NULL);
  g_signal_connect ((gpointer) ProjectTree, "drag_motion",
		    G_CALLBACK (on_ProjectTree_drag_motion), NULL);
  g_signal_connect ((gpointer) ProjectTree, "button_press_event",
		    G_CALLBACK (on_ProjectTree_button_press_event), NULL);
  g_signal_connect ((gpointer) button_building, "drag_begin",
		    G_CALLBACK (on_button_building_drag_begin), NULL);
  g_signal_connect ((gpointer) button_building, "drag_data_get",
		    G_CALLBACK (on_button_drag_data_get), NULL);
  g_signal_connect ((gpointer) button_floor, "drag_begin",
		    G_CALLBACK (on_button_floor_drag_begin), NULL);
  g_signal_connect ((gpointer) button_floor, "drag_data_get",
		    G_CALLBACK (on_button_drag_data_get), NULL);
  g_signal_connect ((gpointer) button_room, "drag_begin",
		    G_CALLBACK (on_button_room_drag_begin), NULL);
  g_signal_connect ((gpointer) button_room, "drag_data_get",
		    G_CALLBACK (on_button_drag_data_get), NULL);
  g_signal_connect ((gpointer) button_junction, "drag_begin",
		    G_CALLBACK (on_button_junction_drag_begin), NULL);
  g_signal_connect ((gpointer) button_junction, "drag_data_get",
		    G_CALLBACK (on_button_drag_data_get), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MainFrame, MainFrame, "MainFrame");
  GLADE_HOOKUP_OBJECT (MainFrame, MainTable, "MainTable");
  GLADE_HOOKUP_OBJECT (MainFrame, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (MainFrame, MainMenu, "MainMenu");
  GLADE_HOOKUP_OBJECT (MainFrame, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (MainFrame, image454, "image454");
  GLADE_HOOKUP_OBJECT (MainFrame, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (MainFrame, new_project, "new_project");
  GLADE_HOOKUP_OBJECT (MainFrame, image455, "image455");
  GLADE_HOOKUP_OBJECT (MainFrame, open_project, "open_project");
  GLADE_HOOKUP_OBJECT (MainFrame, image456, "image456");
  GLADE_HOOKUP_OBJECT (MainFrame, Save, "Save");
  GLADE_HOOKUP_OBJECT (MainFrame, image457, "image457");
  GLADE_HOOKUP_OBJECT (MainFrame, Save_As, "Save_As");
  GLADE_HOOKUP_OBJECT (MainFrame, image458, "image458");
  GLADE_HOOKUP_OBJECT (MainFrame, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (MainFrame, Quitt, "Quitt");
  GLADE_HOOKUP_OBJECT (MainFrame, image459, "image459");
  GLADE_HOOKUP_OBJECT (MainFrame, DeviceData, "DeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image460, "image460");
  GLADE_HOOKUP_OBJECT (MainFrame, DeviceData_menu, "DeviceData_menu");
  GLADE_HOOKUP_OBJECT (MainFrame, ShowDeviceData, "ShowDeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image461, "image461");
  GLADE_HOOKUP_OBJECT (MainFrame, editDeviceData, "editDeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image462, "image462");
  GLADE_HOOKUP_OBJECT (MainFrame, ConvertDeviceData, "ConvertDeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image463, "image463");
  GLADE_HOOKUP_OBJECT (MainFrame, ImportXMLDeviceData, "ImportXMLDeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image464, "image464");
  GLADE_HOOKUP_OBJECT (MainFrame, ExportXMLDeviceData, "ExportXMLDeviceData");
  GLADE_HOOKUP_OBJECT (MainFrame, image465, "image465");
  GLADE_HOOKUP_OBJECT (MainFrame, About, "About");
  GLADE_HOOKUP_OBJECT (MainFrame, image466, "image466");
  GLADE_HOOKUP_OBJECT (MainFrame, statusbar1, "statusbar1");
  GLADE_HOOKUP_OBJECT (MainFrame, PanelLeft, "PanelLeft");
  GLADE_HOOKUP_OBJECT (MainFrame, PanelRight, "PanelRight");
  GLADE_HOOKUP_OBJECT (MainFrame, ScrolledWindowLeft, "ScrolledWindowLeft");
  GLADE_HOOKUP_OBJECT (MainFrame, ProjectTree, "ProjectTree");
  GLADE_HOOKUP_OBJECT (MainFrame, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (MainFrame, handlebox_toolbar, "handlebox_toolbar");
  GLADE_HOOKUP_OBJECT (MainFrame, eventbox_Toolbar, "eventbox_Toolbar");
  GLADE_HOOKUP_OBJECT (MainFrame, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (MainFrame, button_building, "button_building");
  GLADE_HOOKUP_OBJECT (MainFrame, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (MainFrame, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (MainFrame, image154, "image154");
  GLADE_HOOKUP_OBJECT (MainFrame, label10, "label10");
  GLADE_HOOKUP_OBJECT (MainFrame, button_floor, "button_floor");
  GLADE_HOOKUP_OBJECT (MainFrame, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (MainFrame, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (MainFrame, image155, "image155");
  GLADE_HOOKUP_OBJECT (MainFrame, label11, "label11");
  GLADE_HOOKUP_OBJECT (MainFrame, button_room, "button_room");
  GLADE_HOOKUP_OBJECT (MainFrame, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (MainFrame, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (MainFrame, image156, "image156");
  GLADE_HOOKUP_OBJECT (MainFrame, label12, "label12");
  GLADE_HOOKUP_OBJECT (MainFrame, button_junction, "button_junction");
  GLADE_HOOKUP_OBJECT (MainFrame, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (MainFrame, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (MainFrame, image157, "image157");
  GLADE_HOOKUP_OBJECT (MainFrame, label13, "label13");
  GLADE_HOOKUP_OBJECT (MainFrame, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (MainFrame, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (MainFrame, vpaned2, "vpaned2");
  GLADE_HOOKUP_OBJECT (MainFrame, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (MainFrame, scrolledwindow12, "scrolledwindow12");
  GLADE_HOOKUP_OBJECT (MainFrame, viewport3, "viewport3");
  GLADE_HOOKUP_OBJECT (MainFrame, scrolledwindow13, "scrolledwindow13");
  GLADE_HOOKUP_OBJECT (MainFrame, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (MainFrame, label47, "label47");
  GLADE_HOOKUP_OBJECT (MainFrame, label48, "label48");
  GLADE_HOOKUP_OBJECT (MainFrame, label49, "label49");
  GLADE_HOOKUP_OBJECT (MainFrame, hpaned2, "hpaned2");
  GLADE_HOOKUP_OBJECT (MainFrame, vboxGroupAddress, "vboxGroupAddress");
  GLADE_HOOKUP_OBJECT (MainFrame, label57, "label57");
  GLADE_HOOKUP_OBJECT (MainFrame, scrolledwindowGroupAddress,
		       "scrolledwindowGroupAddress");
  GLADE_HOOKUP_OBJECT (MainFrame, GroupAddressTree, "GroupAddressTree");
  GLADE_HOOKUP_OBJECT (MainFrame, vboxTopology, "vboxTopology");
  GLADE_HOOKUP_OBJECT (MainFrame, label58, "label58");
  GLADE_HOOKUP_OBJECT (MainFrame, scrolledwindowTopology,
		       "scrolledwindowTopology");
  GLADE_HOOKUP_OBJECT (MainFrame, TopologyTree, "TopologyTree");
  GLADE_HOOKUP_OBJECT_NO_REF (MainFrame, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (MainFrame), accel_group);

  return MainFrame;
}

GtkWidget *
create_New_Project (void)
{
  GtkWidget *New_Project;
  GdkPixbuf *New_Project_icon_pixbuf;
  GtkWidget *dialog_vbox1;
  GtkWidget *table1;
  GtkWidget *label6;
  GtkWidget *editProjectName;
  GtkWidget *FileChooser;
  GtkWidget *checkCreateProjDir;
  GtkWidget *dialog_action_area1;
  GtkWidget *bCancel;
  GtkWidget *alignment2;
  GtkWidget *hbox1;
  GtkWidget *image131;
  GtkWidget *label1;
  GtkWidget *bOK;
  GtkWidget *alignment3;
  GtkWidget *hbox2;
  GtkWidget *image145;
  GtkWidget *label7;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  New_Project = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (New_Project), _("Neues Projekt anlegen"));
  gtk_window_set_position (GTK_WINDOW (New_Project), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (New_Project), TRUE);
  New_Project_icon_pixbuf = create_pixbuf ("document-new.png");
  if (New_Project_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (New_Project), New_Project_icon_pixbuf);
      gdk_pixbuf_unref (New_Project_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (New_Project),
			    GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (New_Project)->vbox;
  gtk_widget_show (dialog_vbox1);
  gtk_widget_set_size_request (dialog_vbox1, 600, 300);

  table1 = gtk_table_new (2, 3, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), table1, TRUE, TRUE, 0);

  label6 = gtk_label_new (_("Projektname:"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label6), 0, 9);

  editProjectName = gtk_entry_new ();
  gtk_widget_show (editProjectName);
  gtk_table_attach (GTK_TABLE (table1), editProjectName, 1, 2, 1, 2,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 0, 6);
  gtk_tooltips_set_tip (tooltips, editProjectName,
			_("Geben Sie hier den Namen des neuen Projektes ein"),
			NULL);
  gtk_entry_set_max_length (GTK_ENTRY (editProjectName), 50);
  gtk_entry_set_text (GTK_ENTRY (editProjectName), _("Neues Projekt"));

  FileChooser =
    gtk_file_chooser_widget_new (GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_show (FileChooser);
  gtk_table_attach (GTK_TABLE (table1), FileChooser, 0, 3, 0, 1,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  checkCreateProjDir =
    gtk_check_button_new_with_mnemonic (_("Projektordner anlegen"));
  gtk_widget_show (checkCreateProjDir);
  gtk_table_attach (GTK_TABLE (table1), checkCreateProjDir, 2, 3, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 20, 0);
  gtk_tooltips_set_tip (tooltips, checkCreateProjDir,
			_
			("erzeugt ein Projektverzeichnis mit dem Namen des Projektes"),
			NULL);

  dialog_action_area1 = GTK_DIALOG (New_Project)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1),
			     GTK_BUTTONBOX_END);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (New_Project), bCancel,
				GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bCancel, _("Schliesst Dialog ohne Aktion"),
			NULL);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment2);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox1);

  image131 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image131);
  gtk_box_pack_start (GTK_BOX (hbox1), image131, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Abbrechen"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  bOK = gtk_button_new ();
  gtk_widget_show (bOK);
  gtk_dialog_add_action_widget (GTK_DIALOG (New_Project), bOK,
				GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (bOK, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bOK,
			_("schliesst Dialog und übernimmt die Eingaben"),
			NULL);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (bOK), alignment3);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox2);

  image145 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image145);
  gtk_box_pack_start (GTK_BOX (hbox2), image145, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) New_Project, "close",
		    G_CALLBACK (on_New_Project_close), NULL);
  g_signal_connect ((gpointer) bCancel, "clicked",
		    G_CALLBACK (on_bCancel_clicked), NULL);
  g_signal_connect ((gpointer) bOK, "clicked",
		    G_CALLBACK (on_bOK_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (New_Project, New_Project, "New_Project");
  GLADE_HOOKUP_OBJECT_NO_REF (New_Project, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (New_Project, table1, "table1");
  GLADE_HOOKUP_OBJECT (New_Project, label6, "label6");
  GLADE_HOOKUP_OBJECT (New_Project, editProjectName, "editProjectName");
  GLADE_HOOKUP_OBJECT (New_Project, FileChooser, "FileChooser");
  GLADE_HOOKUP_OBJECT (New_Project, checkCreateProjDir, "checkCreateProjDir");
  GLADE_HOOKUP_OBJECT_NO_REF (New_Project, dialog_action_area1,
			      "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (New_Project, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (New_Project, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (New_Project, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (New_Project, image131, "image131");
  GLADE_HOOKUP_OBJECT (New_Project, label1, "label1");
  GLADE_HOOKUP_OBJECT (New_Project, bOK, "bOK");
  GLADE_HOOKUP_OBJECT (New_Project, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (New_Project, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (New_Project, image145, "image145");
  GLADE_HOOKUP_OBJECT (New_Project, label7, "label7");
  GLADE_HOOKUP_OBJECT_NO_REF (New_Project, tooltips, "tooltips");

  gtk_widget_grab_focus (bOK);
  gtk_widget_grab_default (bOK);
  return New_Project;
}

GtkWidget *
create_Open_Project (void)
{
  GtkWidget *Open_Project;
  GdkPixbuf *Open_Project_icon_pixbuf;
  GtkWidget *FileChooser;
  GtkWidget *dialog_action_area2;
  GtkWidget *bCancel;
  GtkWidget *alignment5;
  GtkWidget *hbox4;
  GtkWidget *image147;
  GtkWidget *label9;
  GtkWidget *bOK;
  GtkWidget *alignment4;
  GtkWidget *hbox3;
  GtkWidget *image146;
  GtkWidget *label8;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  Open_Project =
    gtk_file_chooser_dialog_new (_("�\226ffne vorhandenes Projekt"), NULL,
				 GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_position (GTK_WINDOW (Open_Project), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (Open_Project), TRUE);
  Open_Project_icon_pixbuf = create_pixbuf ("document-open.png");
  if (Open_Project_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (Open_Project),
			   Open_Project_icon_pixbuf);
      gdk_pixbuf_unref (Open_Project_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (Open_Project),
			    GDK_WINDOW_TYPE_HINT_DIALOG);

  FileChooser = GTK_DIALOG (Open_Project)->vbox;
  gtk_widget_show (FileChooser);

  dialog_action_area2 = GTK_DIALOG (Open_Project)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2),
			     GTK_BUTTONBOX_END);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (Open_Project), bCancel,
				GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bCancel, _("Schliesst Dialog ohne Aktion"),
			NULL);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment5);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox4);

  image147 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image147);
  gtk_box_pack_start (GTK_BOX (hbox4), image147, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Abbrechen"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  bOK = gtk_button_new ();
  gtk_widget_show (bOK);
  gtk_dialog_add_action_widget (GTK_DIALOG (Open_Project), bOK,
				GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (bOK, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bOK,
			_("schliesst Dialog und übernimmt die Eingaben"),
			NULL);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (bOK), alignment4);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox3);

  image146 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image146);
  gtk_box_pack_start (GTK_BOX (hbox3), image146, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) Open_Project, "destroy",
		    G_CALLBACK (on_Open_Project_destroy), NULL);
  g_signal_connect ((gpointer) bCancel, "clicked",
		    G_CALLBACK (on_bCancel_clicked), NULL);
  g_signal_connect ((gpointer) bOK, "clicked",
		    G_CALLBACK (on_bOK_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Open_Project, Open_Project, "Open_Project");
  GLADE_HOOKUP_OBJECT_NO_REF (Open_Project, FileChooser, "FileChooser");
  GLADE_HOOKUP_OBJECT_NO_REF (Open_Project, dialog_action_area2,
			      "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (Open_Project, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (Open_Project, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Open_Project, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Open_Project, image147, "image147");
  GLADE_HOOKUP_OBJECT (Open_Project, label9, "label9");
  GLADE_HOOKUP_OBJECT (Open_Project, bOK, "bOK");
  GLADE_HOOKUP_OBJECT (Open_Project, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Open_Project, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Open_Project, image146, "image146");
  GLADE_HOOKUP_OBJECT (Open_Project, label8, "label8");
  GLADE_HOOKUP_OBJECT_NO_REF (Open_Project, tooltips, "tooltips");

  gtk_widget_grab_default (bOK);
  return Open_Project;
}

GtkWidget *
create_mnuPopupTree (void)
{
  GtkWidget *mnuPopupTree;
  GtkWidget *mnuChangeName;
  GtkWidget *image199;
  GtkWidget *mnuDeleteGroup;
  GtkWidget *image200;
  GtkWidget *separator1;
  GtkWidget *mnuPropertyGroup;
  GtkWidget *image201;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  mnuPopupTree = gtk_menu_new ();

  mnuChangeName = gtk_image_menu_item_new_with_mnemonic (_("Umbenennen"));
  gtk_widget_show (mnuChangeName);
  gtk_container_add (GTK_CONTAINER (mnuPopupTree), mnuChangeName);
  gtk_tooltips_set_tip (tooltips, mnuChangeName,
			_("zum editieren des Namens"), NULL);

  image199 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image199);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (mnuChangeName),
				 image199);

  mnuDeleteGroup = gtk_image_menu_item_new_with_mnemonic (_("L�\266schen"));
  gtk_widget_show (mnuDeleteGroup);
  gtk_container_add (GTK_CONTAINER (mnuPopupTree), mnuDeleteGroup);
  gtk_tooltips_set_tip (tooltips, mnuDeleteGroup,
			_("l�\266scht diese Gruppe"), NULL);

  image200 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image200);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (mnuDeleteGroup),
				 image200);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (mnuPopupTree), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  mnuPropertyGroup =
    gtk_image_menu_item_new_with_mnemonic (_("Eigenschaften"));
  gtk_widget_show (mnuPropertyGroup);
  gtk_container_add (GTK_CONTAINER (mnuPopupTree), mnuPropertyGroup);
  gtk_tooltips_set_tip (tooltips, mnuPropertyGroup,
			_("zeigt die Eigenschaften dieser Gruppe an"), NULL);

  image201 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image201);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (mnuPropertyGroup),
				 image201);

  g_signal_connect ((gpointer) mnuPopupTree, "button_press_event",
		    G_CALLBACK (on_mnuPopupTree_button_press_event), NULL);
  g_signal_connect ((gpointer) mnuPopupTree, "key_press_event",
		    G_CALLBACK (on_mnuPopupTree_key_press_event), NULL);
  g_signal_connect ((gpointer) mnuChangeName, "activate",
		    G_CALLBACK (on_mnuChangeName_activate), NULL);
  g_signal_connect ((gpointer) mnuDeleteGroup, "activate",
		    G_CALLBACK (on_mnuDeleteGroup_activate), NULL);
  g_signal_connect ((gpointer) mnuPropertyGroup, "activate",
		    G_CALLBACK (on_mnuPropertyGroup_activate), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mnuPopupTree, mnuPopupTree, "mnuPopupTree");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, mnuChangeName, "mnuChangeName");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, image199, "image199");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, mnuDeleteGroup, "mnuDeleteGroup");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, image200, "image200");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, mnuPropertyGroup, "mnuPropertyGroup");
  GLADE_HOOKUP_OBJECT (mnuPopupTree, image201, "image201");
  GLADE_HOOKUP_OBJECT_NO_REF (mnuPopupTree, tooltips, "tooltips");

  return mnuPopupTree;
}

GtkWidget *
create_DlgAddStructureElement (void)
{
  GtkWidget *DlgAddStructureElement;
  GtkWidget *dialog_vbox2;
  GtkWidget *table2;
  GtkWidget *lblText;
  GtkWidget *txtElementName;
  GtkWidget *dialog_action_area3;
  GtkWidget *bCancel;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image202;
  GtkWidget *label15;
  GtkWidget *bOK;
  GtkWidget *alignment11;
  GtkWidget *hbox10;
  GtkWidget *image203;
  GtkWidget *label16;

  DlgAddStructureElement = gtk_dialog_new ();
  gtk_widget_set_size_request (DlgAddStructureElement, 425, 112);
  gtk_window_set_title (GTK_WINDOW (DlgAddStructureElement),
			_("Name des neuen Strukturelementes"));
  gtk_window_set_position (GTK_WINDOW (DlgAddStructureElement),
			   GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (DlgAddStructureElement), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (DlgAddStructureElement), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (DlgAddStructureElement),
				      TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (DlgAddStructureElement),
			    GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (DlgAddStructureElement)->vbox;
  gtk_widget_show (dialog_vbox2);

  table2 = gtk_table_new (2, 1, FALSE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), table2, TRUE, TRUE, 0);

  lblText =
    gtk_label_new (_("Wie m�\266chten Sie das neue Element benennen ?"));
  gtk_widget_show (lblText);
  gtk_table_attach (GTK_TABLE (table2), lblText, 0, 1, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblText), 0.06, 0.5);
  gtk_misc_set_padding (GTK_MISC (lblText), 0, 10);

  txtElementName = gtk_entry_new ();
  gtk_widget_show (txtElementName);
  gtk_table_attach (GTK_TABLE (table2), txtElementName, 0, 1, 1, 2,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 5, 0);
  gtk_entry_set_max_length (GTK_ENTRY (txtElementName), 100);

  dialog_action_area3 = GTK_DIALOG (DlgAddStructureElement)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3),
			     GTK_BUTTONBOX_END);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgAddStructureElement), bCancel,
				GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image202 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image202);
  gtk_box_pack_start (GTK_BOX (hbox9), image202, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("_Abbrechen"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox9), label15, FALSE, FALSE, 0);

  bOK = gtk_button_new ();
  gtk_widget_show (bOK);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgAddStructureElement), bOK,
				GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (bOK, GTK_CAN_DEFAULT);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (bOK), alignment11);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox10);

  image203 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image203);
  gtk_box_pack_start (GTK_BOX (hbox10), image203, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("�\234_bernehmen"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox10), label16, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) DlgAddStructureElement, "destroy",
		    G_CALLBACK (on_DlgAddStructureElement_destroy), NULL);
  g_signal_connect ((gpointer) DlgAddStructureElement, "response",
		    G_CALLBACK (on_DlgAddStructureElement_response), NULL);
  g_signal_connect ((gpointer) bCancel, "clicked",
		    G_CALLBACK (on_bCancel_clicked), NULL);
  g_signal_connect ((gpointer) bOK, "clicked",
		    G_CALLBACK (on_bOK_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (DlgAddStructureElement, DlgAddStructureElement,
			      "DlgAddStructureElement");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgAddStructureElement, dialog_vbox2,
			      "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, table2, "table2");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, lblText, "lblText");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, txtElementName,
		       "txtElementName");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgAddStructureElement, dialog_action_area3,
			      "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, image202, "image202");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, label15, "label15");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, bOK, "bOK");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, image203, "image203");
  GLADE_HOOKUP_OBJECT (DlgAddStructureElement, label16, "label16");

  return DlgAddStructureElement;
}

GtkWidget *
create_DlgConvertDeviceData (void)
{
  GtkWidget *DlgConvertDeviceData;
  GdkPixbuf *DlgConvertDeviceData_icon_pixbuf;
  GtkWidget *dialog_vbox3;
  GtkWidget *table3;
  GtkWidget *txtSourceFile;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *bSelect;
  GtkWidget *ConvertProgress;
  GtkWidget *alignment14;
  GtkWidget *txtDestFile;
  GtkWidget *dialog_action_area4;
  GtkWidget *bCancel;
  GtkWidget *alignment17;
  GtkWidget *hbox15;
  GtkWidget *image471;
  GtkWidget *label23;
  GtkWidget *bConvert;
  GtkWidget *alignment12;
  GtkWidget *hbox11;
  GtkWidget *image467;
  GtkWidget *label17;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  DlgConvertDeviceData = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (DlgConvertDeviceData),
			_("Stammdaten Konverter"));
  gtk_window_set_position (GTK_WINDOW (DlgConvertDeviceData),
			   GTK_WIN_POS_CENTER);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (DlgConvertDeviceData),
				      TRUE);
  DlgConvertDeviceData_icon_pixbuf = create_pixbuf ("converter_icon.png");
  if (DlgConvertDeviceData_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (DlgConvertDeviceData),
			   DlgConvertDeviceData_icon_pixbuf);
      gdk_pixbuf_unref (DlgConvertDeviceData_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (DlgConvertDeviceData),
			    GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (DlgConvertDeviceData)->vbox;
  gtk_widget_show (dialog_vbox3);

  table3 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), table3, TRUE, TRUE, 0);

  txtSourceFile = gtk_entry_new ();
  gtk_widget_show (txtSourceFile);
  gtk_table_attach (GTK_TABLE (table3), txtSourceFile, 1, 2, 0, 1,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, txtSourceFile,
			_
			("Wählen Sie hier die zu konvertierende *._vd Datei aus. "),
			NULL);

  label20 = gtk_label_new (_("Name der Zieldatei:"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table3), label20, 0, 1, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label19 = gtk_label_new (_("zu konvertierende Datei auswählen:"));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table3), label19, 0, 1, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 11);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  bSelect = gtk_button_new_with_mnemonic (_("Durchsuchen..."));
  gtk_widget_show (bSelect);
  gtk_table_attach (GTK_TABLE (table3), bSelect, 2, 3, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 7, 0);
  gtk_tooltips_set_tip (tooltips, bSelect,
			_("�\266ffnet den Dateiauswahldialog"), NULL);

  ConvertProgress = gtk_progress_bar_new ();
  gtk_widget_show (ConvertProgress);
  gtk_table_attach (GTK_TABLE (table3), ConvertProgress, 0, 3, 2, 3,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 14);
  gtk_progress_bar_set_pulse_step (GTK_PROGRESS_BAR (ConvertProgress), 0);

  alignment14 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment14);
  gtk_table_attach (GTK_TABLE (table3), alignment14, 1, 3, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment14), 0, 0, 0, 260);

  txtDestFile = gtk_entry_new ();
  gtk_widget_show (txtDestFile);
  gtk_container_add (GTK_CONTAINER (alignment14), txtDestFile);
  gtk_tooltips_set_tip (tooltips, txtDestFile,
			_
			("Geben Sie hier den Namen der konvertierten Datei ein. Ein Dateierweiterung ist nicht notwendig."),
			NULL);
  gtk_entry_set_max_length (GTK_ENTRY (txtDestFile), 30);

  dialog_action_area4 = GTK_DIALOG (DlgConvertDeviceData)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4),
			     GTK_BUTTONBOX_END);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgConvertDeviceData), bCancel,
				GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bCancel,
			_("beendet den Konverter und schließt den Dialog"),
			NULL);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment17);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox15);

  image471 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image471);
  gtk_box_pack_start (GTK_BOX (hbox15), image471, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Schließen"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox15), label23, FALSE, FALSE, 0);

  bConvert = gtk_button_new ();
  gtk_widget_show (bConvert);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgConvertDeviceData), bConvert,
				0);
  GTK_WIDGET_SET_FLAGS (bConvert, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bConvert,
			_("startet den Konvertierungsvorgang"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (bConvert), FALSE);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (bConvert), alignment12);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox11);

  image467 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image467);
  gtk_box_pack_start (GTK_BOX (hbox11), image467, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Konvertieren"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox11), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bSelect, "clicked",
		    G_CALLBACK (on_bSelect_clicked), NULL);
  g_signal_connect ((gpointer) bCancel, "clicked",
		    G_CALLBACK (on_bCancel_clicked), NULL);
  g_signal_connect ((gpointer) bConvert, "clicked",
		    G_CALLBACK (on_bConvert_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (DlgConvertDeviceData, DlgConvertDeviceData,
			      "DlgConvertDeviceData");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgConvertDeviceData, dialog_vbox3,
			      "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, table3, "table3");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, txtSourceFile, "txtSourceFile");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, label20, "label20");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, label19, "label19");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, bSelect, "bSelect");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, ConvertProgress,
		       "ConvertProgress");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, txtDestFile, "txtDestFile");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgConvertDeviceData, dialog_action_area4,
			      "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, image471, "image471");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, label23, "label23");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, bConvert, "bConvert");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, image467, "image467");
  GLADE_HOOKUP_OBJECT (DlgConvertDeviceData, label17, "label17");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgConvertDeviceData, tooltips, "tooltips");

  return DlgConvertDeviceData;
}

GtkWidget *
create_DlgFileChooser (void)
{
  GtkWidget *DlgFileChooser;
  GdkPixbuf *DlgFileChooser_icon_pixbuf;
  GtkWidget *dialog_vbox4;
  GtkWidget *dialog_action_area5;
  GtkWidget *bCancel;
  GtkWidget *alignment16;
  GtkWidget *hbox14;
  GtkWidget *image470;
  GtkWidget *label22;
  GtkWidget *bApply;
  GtkWidget *alignment15;
  GtkWidget *hbox13;
  GtkWidget *image469;
  GtkWidget *label21;

  DlgFileChooser =
    gtk_file_chooser_dialog_new (_("Datei auswählen..."), NULL,
				 GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_modal (GTK_WINDOW (DlgFileChooser), TRUE);
  DlgFileChooser_icon_pixbuf = create_pixbuf ("document-open.png");
  if (DlgFileChooser_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (DlgFileChooser),
			   DlgFileChooser_icon_pixbuf);
      gdk_pixbuf_unref (DlgFileChooser_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (DlgFileChooser),
			    GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox4 = GTK_DIALOG (DlgFileChooser)->vbox;
  gtk_widget_show (dialog_vbox4);

  dialog_action_area5 = GTK_DIALOG (DlgFileChooser)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5),
			     GTK_BUTTONBOX_END);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgFileChooser), bCancel,
				GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment16);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox14);

  image470 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image470);
  gtk_box_pack_start (GTK_BOX (hbox14), image470, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Abbrechen"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox14), label22, FALSE, FALSE, 0);

  bApply = gtk_button_new ();
  gtk_widget_show (bApply);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgFileChooser), bApply,
				GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (bApply, GTK_CAN_DEFAULT);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (bApply), alignment15);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox13);

  image469 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image469);
  gtk_box_pack_start (GTK_BOX (hbox13), image469, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("�\234bernehmen"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox13), label21, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (DlgFileChooser, DlgFileChooser,
			      "DlgFileChooser");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgFileChooser, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgFileChooser, dialog_action_area5,
			      "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, image470, "image470");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, label22, "label22");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, bApply, "bApply");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, image469, "image469");
  GLADE_HOOKUP_OBJECT (DlgFileChooser, label21, "label21");

  gtk_widget_grab_default (bApply);
  return DlgFileChooser;
}

GtkWidget *
create_DlgImportFromXML (void)
{
  GtkWidget *DlgImportFromXML;
  GdkPixbuf *DlgImportFromXML_icon_pixbuf;
  GtkWidget *dialog_vbox5;
  GtkWidget *table4;
  GtkWidget *label26;
  GtkWidget *txtSourceFile;
  GtkWidget *ImportProgress;
  GtkWidget *bSelect;
  GtkWidget *ManufacturerCount;
  GtkWidget *Product_Count;
  GtkWidget *App_Count;
  GtkWidget *Com_Count;
  GtkWidget *Param_Count;
  GtkWidget *image474;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *dialog_action_area6;
  GtkWidget *bCancel;
  GtkWidget *alignment19;
  GtkWidget *hbox17;
  GtkWidget *image473;
  GtkWidget *label25;
  GtkWidget *bImport;
  GtkWidget *alignment18;
  GtkWidget *hbox16;
  GtkWidget *image472;
  GtkWidget *label24;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  DlgImportFromXML = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (DlgImportFromXML),
			_("Datenintegration in Datenbank"));
  DlgImportFromXML_icon_pixbuf = create_pixbuf ("package-x-generic.png");
  if (DlgImportFromXML_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (DlgImportFromXML),
			   DlgImportFromXML_icon_pixbuf);
      gdk_pixbuf_unref (DlgImportFromXML_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (DlgImportFromXML),
			    GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox5 = GTK_DIALOG (DlgImportFromXML)->vbox;
  gtk_widget_show (dialog_vbox5);

  table4 = gtk_table_new (7, 4, FALSE);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), table4, TRUE, TRUE, 0);

  label26 = gtk_label_new (_("XML-Datei:"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table4), label26, 0, 1, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 11);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  txtSourceFile = gtk_entry_new ();
  gtk_widget_show (txtSourceFile);
  gtk_table_attach (GTK_TABLE (table4), txtSourceFile, 1, 3, 0, 1,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, txtSourceFile,
			_
			("Wählen Sie hier die zu importierende Datenquelle aus"),
			NULL);

  ImportProgress = gtk_progress_bar_new ();
  gtk_widget_show (ImportProgress);
  gtk_table_attach (GTK_TABLE (table4), ImportProgress, 0, 4, 6, 7,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 14);

  bSelect = gtk_button_new_with_mnemonic (_("Durchsuchen..."));
  gtk_widget_show (bSelect);
  gtk_table_attach (GTK_TABLE (table4), bSelect, 3, 4, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 7, 0);
  gtk_tooltips_set_tip (tooltips, bSelect,
			_("�\266ffnet den Dateiauswahldialog"), NULL);

  ManufacturerCount = gtk_label_new (_("ManufacturerCount"));
  gtk_widget_show (ManufacturerCount);
  gtk_table_attach (GTK_TABLE (table4), ManufacturerCount, 1, 2, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (ManufacturerCount), 0, 0.5);

  Product_Count = gtk_label_new (_("Product_Count"));
  gtk_widget_show (Product_Count);
  gtk_table_attach (GTK_TABLE (table4), Product_Count, 1, 2, 2, 3,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Product_Count), 0, 0.5);

  App_Count = gtk_label_new (_("App_Count"));
  gtk_widget_show (App_Count);
  gtk_table_attach (GTK_TABLE (table4), App_Count, 1, 2, 3, 4,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (App_Count), 0, 0.5);

  Com_Count = gtk_label_new (_("Com_Count"));
  gtk_widget_show (Com_Count);
  gtk_table_attach (GTK_TABLE (table4), Com_Count, 1, 2, 4, 5,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Com_Count), 0, 0.5);

  Param_Count = gtk_label_new (_("Param_Count"));
  gtk_widget_show (Param_Count);
  gtk_table_attach (GTK_TABLE (table4), Param_Count, 1, 2, 5, 6,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Param_Count), 0, 0.5);

  image474 = create_pixmap (DlgImportFromXML, "sql.png");
  gtk_widget_show (image474);
  gtk_table_attach (GTK_TABLE (table4), image474, 2, 4, 1, 6,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label27 = gtk_label_new (_("Hersteller:"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table4), label27, 0, 1, 1, 2,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 3);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label28 = gtk_label_new (_("Produkte:"));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table4), label28, 0, 1, 2, 3,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 3);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label29 = gtk_label_new (_("Applikationen:"));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table4), label29, 0, 1, 3, 4,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 3);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new (_("Kommunikationsobjekte:"));
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table4), label30, 0, 1, 4, 5,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 3);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  label31 = gtk_label_new (_("Parameter:"));
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table4), label31, 0, 1, 5, 6,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (0), 10, 3);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  dialog_action_area6 = GTK_DIALOG (DlgImportFromXML)->action_area;
  gtk_widget_show (dialog_action_area6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area6),
			     GTK_BUTTONBOX_END);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgImportFromXML), bCancel,
				GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bCancel, _("beendet den Dialog"), NULL);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment19);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox17);

  image473 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image473);
  gtk_box_pack_start (GTK_BOX (hbox17), image473, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Schließen"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox17), label25, FALSE, FALSE, 0);

  bImport = gtk_button_new ();
  gtk_widget_show (bImport);
  gtk_dialog_add_action_widget (GTK_DIALOG (DlgImportFromXML), bImport,
				GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (bImport, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, bImport, _("Startet den Import der Daten"),
			NULL);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (bImport), alignment18);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox16);

  image472 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image472);
  gtk_box_pack_start (GTK_BOX (hbox16), image472, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Einlesen"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox16), label24, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bSelect, "clicked",
		    G_CALLBACK (on_bSelect_clicked), NULL);
  g_signal_connect ((gpointer) bCancel, "clicked",
		    G_CALLBACK (on_bCancel_clicked), NULL);
  g_signal_connect ((gpointer) bImport, "clicked",
		    G_CALLBACK (on_bImport_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (DlgImportFromXML, DlgImportFromXML,
			      "DlgImportFromXML");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgImportFromXML, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, table4, "table4");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, label26, "label26");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, txtSourceFile, "txtSourceFile");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, ImportProgress, "ImportProgress");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, bSelect, "bSelect");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, ManufacturerCount,
		       "ManufacturerCount");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, Product_Count, "Product_Count");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, App_Count, "App_Count");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, Com_Count, "Com_Count");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, Param_Count, "Param_Count");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, image474, "image474");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, label27, "label27");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, label28, "label28");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, label29, "label29");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, label30, "label30");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, label31, "label31");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgImportFromXML, dialog_action_area6,
			      "dialog_action_area6");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, image473, "image473");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, label25, "label25");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, bImport, "bImport");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, image472, "image472");
  GLADE_HOOKUP_OBJECT (DlgImportFromXML, label24, "label24");
  GLADE_HOOKUP_OBJECT_NO_REF (DlgImportFromXML, tooltips, "tooltips");

  return DlgImportFromXML;
}

GtkWidget *
create_DeviceDataWindow (void)
{
  GtkWidget *DeviceDataWindow;
  GtkWidget *scrolledwindow5;
  GtkWidget *viewport2;
  GtkWidget *vpaned1;
  GtkWidget *table5;
  GtkWidget *lblProgramVersion;
  GtkWidget *lblPEI;
  GtkWidget *lblApplicationName;
  GtkWidget *frameApps;
  GtkWidget *alignment29;
  GtkWidget *scrolledwindow15;
  GtkWidget *ListApps;
  GtkWidget *lblApps;
  GtkWidget *frameProducts;
  GtkWidget *alignment28;
  GtkWidget *scrolledwindowProducts;
  GtkWidget *ListProducts;
  GtkWidget *lblProducts;
  GtkWidget *hseparator1;
  GtkWidget *frameManufacturer;
  GtkWidget *alignment21;
  GtkWidget *scrolledwindowManufacturer;
  GtkWidget *ListManufacturer;
  GtkWidget *label41;
  GtkWidget *table6;
  GtkWidget *hbuttonbox2;
  GtkWidget *bCancel;
  GtkWidget *alignment24;
  GtkWidget *hbox18;
  GtkWidget *image475;
  GtkWidget *label44;
  GtkWidget *bClose;
  GtkWidget *alignment25;
  GtkWidget *hbox19;
  GtkWidget *image476;
  GtkWidget *label45;
  GtkWidget *frame3;
  GtkWidget *alignment30;
  GtkWidget *scrolledwindow16;
  GtkWidget *ListComObj;
  GtkWidget *label56;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  DeviceDataWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (DeviceDataWindow),
			_("Datenbasis zuordnen"));
  gtk_window_set_default_size (GTK_WINDOW (DeviceDataWindow), 845, 650);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (DeviceDataWindow), TRUE);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_container_add (GTK_CONTAINER (DeviceDataWindow), scrolledwindow5);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), viewport2);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_show (vpaned1);
  gtk_container_add (GTK_CONTAINER (viewport2), vpaned1);

  table5 = gtk_table_new (4, 3, FALSE);
  gtk_widget_show (table5);
  gtk_paned_pack1 (GTK_PANED (vpaned1), table5, FALSE, TRUE);

  lblProgramVersion = gtk_label_new (_("ProgramVersion: x.y"));
  gtk_widget_show (lblProgramVersion);
  gtk_table_attach (GTK_TABLE (table5), lblProgramVersion, 1, 2, 3, 4,
		    (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 5);
  gtk_widget_set_size_request (lblProgramVersion, 340, -1);
  gtk_misc_set_alignment (GTK_MISC (lblProgramVersion), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lblProgramVersion), 4, 7);

  lblPEI = gtk_label_new (_("PEI-Prog.-Version:"));
  gtk_widget_show (lblPEI);
  gtk_table_attach (GTK_TABLE (table5), lblPEI, 2, 3, 3, 4,
		    (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 5);
  gtk_widget_set_size_request (lblPEI, 160, -1);
  gtk_misc_set_alignment (GTK_MISC (lblPEI), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lblPEI), 4, 7);

  lblApplicationName = gtk_label_new (_("ApplicationName: xxyy"));
  gtk_widget_show (lblApplicationName);
  gtk_table_attach (GTK_TABLE (table5), lblApplicationName, 0, 1, 3, 4,
		    (GtkAttachOptions) (0), (GtkAttachOptions) (0), 0, 5);
  gtk_widget_set_size_request (lblApplicationName, 300, -1);
  gtk_label_set_line_wrap (GTK_LABEL (lblApplicationName), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lblApplicationName), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (lblApplicationName), 4, 7);

  frameApps = gtk_frame_new (NULL);
  gtk_widget_show (frameApps);
  gtk_table_attach (GTK_TABLE (table5), frameApps, 0, 3, 2, 3,
		    (GtkAttachOptions) (0),
		    (GtkAttachOptions) (GTK_FILL), 4, 4);
  gtk_widget_set_size_request (frameApps, 800, -1);
  gtk_frame_set_label_align (GTK_FRAME (frameApps), 0.02, 0.5);

  alignment29 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (frameApps), alignment29);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment29), 9, 0, 0, 0);

  scrolledwindow15 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow15);
  gtk_container_add (GTK_CONTAINER (alignment29), scrolledwindow15);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow15),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  ListApps = gtk_tree_view_new ();
  gtk_widget_show (ListApps);
  gtk_container_add (GTK_CONTAINER (scrolledwindow15), ListApps);
  gtk_widget_set_size_request (ListApps, -1, 130);
  gtk_tooltips_set_tip (tooltips, ListApps,
			_
			("Auswahl der zur Verfügung stehenden Applikationen des gewählten Produkts"),
			NULL);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (ListApps), FALSE);

  lblApps = gtk_label_new (_("<b> Applikationen von xxxx </b>"));
  gtk_widget_show (lblApps);
  gtk_frame_set_label_widget (GTK_FRAME (frameApps), lblApps);
  gtk_label_set_use_markup (GTK_LABEL (lblApps), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lblApps), 0, 0.5);

  frameProducts = gtk_frame_new (NULL);
  gtk_widget_show (frameProducts);
  gtk_table_attach (GTK_TABLE (table5), frameProducts, 1, 3, 0, 1,
		    (GtkAttachOptions) (0), (GtkAttachOptions) (0), 4, 4);
  gtk_widget_set_size_request (frameProducts, 500, -1);
  gtk_frame_set_label_align (GTK_FRAME (frameProducts), 0.02, 0.5);

  alignment28 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (frameProducts), alignment28);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment28), 9, 0, 0, 0);

  scrolledwindowProducts = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindowProducts);
  gtk_container_add (GTK_CONTAINER (alignment28), scrolledwindowProducts);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW
				  (scrolledwindowProducts),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  ListProducts = gtk_tree_view_new ();
  gtk_widget_show (ListProducts);
  gtk_container_add (GTK_CONTAINER (scrolledwindowProducts), ListProducts);
  gtk_widget_set_size_request (ListProducts, -1, 130);
  gtk_tooltips_set_tip (tooltips, ListProducts,
			_
			("Auswahl der zur Verfügung stehenden Produkte des gewählten Herstellers"),
			NULL);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (ListProducts), FALSE);

  lblProducts = gtk_label_new (_("<b> Produkte von xxxx </b>"));
  gtk_widget_show (lblProducts);
  gtk_frame_set_label_widget (GTK_FRAME (frameProducts), lblProducts);
  gtk_label_set_use_markup (GTK_LABEL (lblProducts), TRUE);
  gtk_misc_set_alignment (GTK_MISC (lblProducts), 0, 0.5);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_table_attach (GTK_TABLE (table5), hseparator1, 0, 3, 1, 2,
		    (GtkAttachOptions) (0), (GtkAttachOptions) (0), 4, 10);
  gtk_widget_set_size_request (hseparator1, 800, -1);

  frameManufacturer = gtk_frame_new (NULL);
  gtk_widget_show (frameManufacturer);
  gtk_table_attach (GTK_TABLE (table5), frameManufacturer, 0, 1, 0, 1,
		    (GtkAttachOptions) (0), (GtkAttachOptions) (0), 4, 4);
  gtk_widget_set_size_request (frameManufacturer, 300, -1);
  gtk_frame_set_label_align (GTK_FRAME (frameManufacturer), 0.02, 0.5);

  alignment21 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (frameManufacturer), alignment21);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment21), 9, 0, 0, 0);

  scrolledwindowManufacturer = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindowManufacturer);
  gtk_container_add (GTK_CONTAINER (alignment21), scrolledwindowManufacturer);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW
				  (scrolledwindowManufacturer),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  ListManufacturer = gtk_tree_view_new ();
  gtk_widget_show (ListManufacturer);
  gtk_container_add (GTK_CONTAINER (scrolledwindowManufacturer),
		     ListManufacturer);
  gtk_widget_set_size_request (ListManufacturer, -1, 130);
  gtk_tooltips_set_tip (tooltips, ListManufacturer,
			_("Auswahl der zur Verfügung stehenden Hersteller"),
			NULL);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (ListManufacturer), FALSE);

  label41 = gtk_label_new (_("<b>Hersteller</b>"));
  gtk_widget_show (label41);
  gtk_frame_set_label_widget (GTK_FRAME (frameManufacturer), label41);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label41), 0, 0.5);

  table6 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table6);
  gtk_paned_pack2 (GTK_PANED (vpaned1), table6, TRUE, FALSE);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_table_attach (GTK_TABLE (table6), hbuttonbox2, 0, 3, 2, 3,
		    (GtkAttachOptions) (0), (GtkAttachOptions) (0), 4, 10);
  gtk_widget_set_size_request (hbuttonbox2, 800, -1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox2), 5);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), bCancel);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment24);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox18);

  image475 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image475);
  gtk_box_pack_start (GTK_BOX (hbox18), image475, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Abbrechen"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox18), label44, FALSE, FALSE, 0);

  bClose = gtk_button_new ();
  gtk_widget_show (bClose);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), bClose);
  GTK_WIDGET_SET_FLAGS (bClose, GTK_CAN_DEFAULT);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (bClose), alignment25);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox19);

  image476 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image476);
  gtk_box_pack_start (GTK_BOX (hbox19), image476, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Schließen"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox19), label45, FALSE, FALSE, 0);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_table_attach (GTK_TABLE (table6), frame3, 0, 3, 0, 2,
		    (GtkAttachOptions) (0),
		    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
		    4, 1);
  gtk_widget_set_size_request (frame3, 800, -1);
  gtk_frame_set_label_align (GTK_FRAME (frame3), 0.02, 0.5);

  alignment30 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (frame3), alignment30);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment30), 9, 0, 0, 0);

  scrolledwindow16 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow16);
  gtk_container_add (GTK_CONTAINER (alignment30), scrolledwindow16);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow16),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  ListComObj = gtk_tree_view_new ();
  gtk_widget_show (ListComObj);
  gtk_container_add (GTK_CONTAINER (scrolledwindow16), ListComObj);
  gtk_widget_set_size_request (ListComObj, -1, 130);
  gtk_tooltips_set_tip (tooltips, ListComObj,
			_
			("Auswahl der zur Verfügung stehenden Kommunikationsobjekte"),
			NULL);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (ListComObj), FALSE);

  label56 = gtk_label_new (_("<b> Objekte </b>"));
  gtk_widget_show (label56);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label56);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  g_signal_connect ((gpointer) ListApps, "cursor_changed",
		    G_CALLBACK (on_ListApps_cursor_changed), NULL);
  g_signal_connect ((gpointer) ListProducts, "cursor_changed",
		    G_CALLBACK (on_ListProducts_cursor_changed), NULL);
  g_signal_connect ((gpointer) ListManufacturer, "cursor_changed",
		    G_CALLBACK (on_ListManufacturer_cursor_changed), NULL);
  g_signal_connect ((gpointer) bCancel, "clicked",
		    G_CALLBACK (on_bCancel_clicked), NULL);
  g_signal_connect ((gpointer) bClose, "clicked",
		    G_CALLBACK (on_bClose_clicked), NULL);
  g_signal_connect ((gpointer) ListComObj, "row_activated",
		    G_CALLBACK (on_ListManufacturer_row_activated), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (DeviceDataWindow, DeviceDataWindow,
			      "DeviceDataWindow");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, vpaned1, "vpaned1");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, table5, "table5");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, lblProgramVersion,
		       "lblProgramVersion");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, lblPEI, "lblPEI");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, lblApplicationName,
		       "lblApplicationName");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, frameApps, "frameApps");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, scrolledwindow15,
		       "scrolledwindow15");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, ListApps, "ListApps");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, lblApps, "lblApps");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, frameProducts, "frameProducts");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, scrolledwindowProducts,
		       "scrolledwindowProducts");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, ListProducts, "ListProducts");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, lblProducts, "lblProducts");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, frameManufacturer,
		       "frameManufacturer");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, scrolledwindowManufacturer,
		       "scrolledwindowManufacturer");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, ListManufacturer,
		       "ListManufacturer");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, label41, "label41");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, table6, "table6");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, image475, "image475");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, label44, "label44");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, bClose, "bClose");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, image476, "image476");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, label45, "label45");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, scrolledwindow16,
		       "scrolledwindow16");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, ListComObj, "ListComObj");
  GLADE_HOOKUP_OBJECT (DeviceDataWindow, label56, "label56");
  GLADE_HOOKUP_OBJECT_NO_REF (DeviceDataWindow, tooltips, "tooltips");

  gtk_widget_grab_default (bClose);
  return DeviceDataWindow;
}

GtkWidget *
create_ParameterWindow (void)
{
  GtkWidget *ParameterWindow;
  GtkWidget *table7;
  GtkWidget *hbuttonbox3;
  GtkWidget *bOK;
  GtkWidget *alignment33;
  GtkWidget *hbox22;
  GtkWidget *image479;
  GtkWidget *label61;
  GtkWidget *bCancel;
  GtkWidget *alignment34;
  GtkWidget *hbox23;
  GtkWidget *image480;
  GtkWidget *label62;
  GtkWidget *bDefault;
  GtkWidget *alignment35;
  GtkWidget *hbox24;
  GtkWidget *image481;
  GtkWidget *label63;
  GtkWidget *scrolledwindowParamListLeft;
  GtkWidget *ParamLeftList;
  GtkWidget *scrolledwindow18;
  GtkWidget *viewport4;

  ParameterWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ParameterWindow),
			_("Anzeige Adresse und Name der Applikation"));

  table7 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table7);
  gtk_container_add (GTK_CONTAINER (ParameterWindow), table7);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_table_attach (GTK_TABLE (table7), hbuttonbox3, 0, 2, 1, 2,
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
		    (GtkAttachOptions) (GTK_FILL), 6, 20);
  gtk_widget_set_size_request (hbuttonbox3, 800, -1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox3), 5);

  bOK = gtk_button_new ();
  gtk_widget_show (bOK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), bOK);
  GTK_WIDGET_SET_FLAGS (bOK, GTK_CAN_DEFAULT);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (bOK), alignment33);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox22);

  image479 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image479);
  gtk_box_pack_start (GTK_BOX (hbox22), image479, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox22), label61, FALSE, FALSE, 0);

  bCancel = gtk_button_new ();
  gtk_widget_show (bCancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), bCancel);
  GTK_WIDGET_SET_FLAGS (bCancel, GTK_CAN_DEFAULT);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (bCancel), alignment34);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox23);

  image480 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image480);
  gtk_box_pack_start (GTK_BOX (hbox23), image480, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("Abbrechen"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox23), label62, FALSE, FALSE, 0);

  bDefault = gtk_button_new ();
  gtk_widget_show (bDefault);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), bDefault);
  GTK_WIDGET_SET_FLAGS (bDefault, GTK_CAN_DEFAULT);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (bDefault), alignment35);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox24);

  image481 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image481);
  gtk_box_pack_start (GTK_BOX (hbox24), image481, FALSE, FALSE, 0);
  gtk_widget_set_size_request (image481, 20, 20);

  label63 = gtk_label_new_with_mnemonic (_("Standard"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox24), label63, FALSE, FALSE, 0);

  scrolledwindowParamListLeft = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindowParamListLeft);
  gtk_table_attach (GTK_TABLE (table7), scrolledwindowParamListLeft, 0, 1, 0,
		    1, (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW
				  (scrolledwindowParamListLeft),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  ParamLeftList = gtk_tree_view_new ();
  gtk_widget_show (ParamLeftList);
  gtk_container_add (GTK_CONTAINER (scrolledwindowParamListLeft),
		     ParamLeftList);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (ParamLeftList), FALSE);

  scrolledwindow18 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow18);
  gtk_table_attach (GTK_TABLE (table7), scrolledwindow18, 1, 2, 0, 1,
		    (GtkAttachOptions) (GTK_FILL),
		    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow18),
				  GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport4 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow18), viewport4);

  g_signal_connect ((gpointer) bOK, "clicked",
		    G_CALLBACK (on_bCancel_clicked), NULL);
  g_signal_connect ((gpointer) bCancel, "clicked",
		    G_CALLBACK (on_bClose_clicked), NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ParameterWindow, ParameterWindow,
			      "ParameterWindow");
  GLADE_HOOKUP_OBJECT (ParameterWindow, table7, "table7");
  GLADE_HOOKUP_OBJECT (ParameterWindow, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (ParameterWindow, bOK, "bOK");
  GLADE_HOOKUP_OBJECT (ParameterWindow, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (ParameterWindow, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (ParameterWindow, image479, "image479");
  GLADE_HOOKUP_OBJECT (ParameterWindow, label61, "label61");
  GLADE_HOOKUP_OBJECT (ParameterWindow, bCancel, "bCancel");
  GLADE_HOOKUP_OBJECT (ParameterWindow, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (ParameterWindow, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (ParameterWindow, image480, "image480");
  GLADE_HOOKUP_OBJECT (ParameterWindow, label62, "label62");
  GLADE_HOOKUP_OBJECT (ParameterWindow, bDefault, "bDefault");
  GLADE_HOOKUP_OBJECT (ParameterWindow, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (ParameterWindow, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (ParameterWindow, image481, "image481");
  GLADE_HOOKUP_OBJECT (ParameterWindow, label63, "label63");
  GLADE_HOOKUP_OBJECT (ParameterWindow, scrolledwindowParamListLeft,
		       "scrolledwindowParamListLeft");
  GLADE_HOOKUP_OBJECT (ParameterWindow, ParamLeftList, "ParamLeftList");
  GLADE_HOOKUP_OBJECT (ParameterWindow, scrolledwindow18, "scrolledwindow18");
  GLADE_HOOKUP_OBJECT (ParameterWindow, viewport4, "viewport4");

  gtk_widget_grab_default (bCancel);
  return ParameterWindow;
}
